### ISSUE TITLE
Redis cache plugin (2.0.0) UI broken 

### ISSUE THREAD

**Issue by ivank** [gravitee-io/issues#10082]
## Describe the bug
[gravitee-resource-cache-redis (version 2.0.0)](https://github.com/gravitee-io/gravitee-resource-cache-redis/releases/tag/2.0.0) does not work with apim management ui. (4.4.5 and the latest 4.4.10)

## To Reproduce

Add the plugin via helm charts:

```yaml
1. ...
gateway:
  additionalPlugins:
- https://download.gravitee.io/graviteeio-apim/plugins/resources/gravitee-resource-cache-redis/gravitee-resource-cache-redis-2.0.0.zip
1. ...
api:
  additionalPlugins:
- https://download.gravitee.io/graviteeio-apim/plugins/resources/gravitee-resource-cache-redis/gravitee-resource-cache-redis-2.0.0.zip
1. ...
```

UI is totally busted on 4.4.5 . When upgraded to (latest) 4.4.10, the UI appears, but cannot be saved as the section for standalone configuration is not visible at all.

## Expected behaviour
UI to work with the latest cache resource

## Current behaviour
UI does not allow cache resource to be saved

## Environment

APIM 4.4.10
APIM 4.4.5
gravitee-resource-cache-redis 2.0.0

## Workarounds

changing to gravitee-resource-cache-redis 1.5.0 allows it to work
