### ISSUE TITLE
[APIM] Gateway returns not found on correct path

### ISSUE THREAD

**Issue by alperalpdogan2** [gravitee-io/issues#10112]
## Describe the bug
I'm trying to use domain.com/gateway for my base url for the gateway. But when path is used in the ingress for the gateway all apis returns 404 with to following body "No context-path matches the request URI."

## To Reproduce
Download helm chart version 4.3.13.
Use the below configuration for the gateway ingress.

```
  ingress:
    enabled: true
    pathType: Prefix
    path: /gateway
    ingressClassName: ""
    hosts:
      - domain.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/issuer: "letsencrypt-nginx"
      kubernetes.io/tls-acme: "true"
    tls:
     - hosts:
         - domain.com
       secretName: apim-custom-gateway-cert

```

## Expected behaviour
https://domain.com/gateway/api/action should return the response from the backend.

## Current behaviour
https://domain.com/gateway/api/action returns 
404 with No context-path matches the request URI.

**Comment by alperalpdogan2** [comment]
Well here is the ingress configuration that works for those who have similar issue.

```
  ingress:
    enabled: true
    pathType: Prefix
    path: /gateway(/|$)(.*)
    ingressClassName: ""
    hosts:
      - domain.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/issuer: "letsencrypt-nginx"
      kubernetes.io/tls-acme: "true"
    tls:
     - hosts:
         - domain.com
       secretName: apim-custom-cert

```
