### ISSUE TITLE
[management api] apply changes to gravitee.yml?

### ISSUE THREAD

**Issue by PierrickI3** [gravitee-io/issues#1350]
If I modify the gravitee.yml file, are the changes taking effect immediately?
I tried to reboot the container I used but it overwrote my changes.
Do I need to restart the daemon?

**Comment by NicolasGeraud** [comment]
Hi,
gravitee (gateway or management-api) needs to be restarted to take account of the new yaml.

Are you using the default gravitee docker files ?

**Comment by PierrickI3** [comment]
Hi Nicolas,

I deployed the docker images in kubernetes containers. Is there a command line I can use to restart the management-api without rebooting?

**Comment by PierrickI3** [comment]
Or let me ask it this way, I have followed this guide to add the keycloak integration: https://docs.gravitee.io/apim_installguide_authentication_keycloak.html and I need to change the gravitee.yml file.
Is there a way to use environment variables or the API to add the oauth2 section instead of having to modify the gravitee.yml file?

**Comment by NicolasGeraud** [comment]
sure you can : https://docs.gravitee.io/apim_installguide_management_api_configuration.html#how_to_configure

**Comment by PierrickI3** [comment]
so let's say I wanted to add this to the security/providers section in gravitee.yml:

```
- type: oauth2
  clientId: gravitee
  clientSecret: 3aea136c-f056-49a8-80f4-a6ea521b0c94
  tokenEndpoint: http://localhost:8080/auth/realms/master/protocol/openid-connect/token
  tokenIntrospectionEndpoint: http://localhost:8080/auth/realms/master/protocol/openid-connect/token/introspect
  userInfoEndpoint: http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
  accessTokenProperty: access_token
  authorizationHeader: "Bearer %s"
  mapping:
    id: sub
    email: email
    lastname: family_name
    firstname: given_name
```

* Since this is a list, how can this be handled in an environment variable?  Should the `type` item be set like this: `GRAVITEE_SECURITY_PROVIDERS_0_TYPE = oauth2` ?

Thanks!
