### ISSUE TITLE
No option to create users

### ISSUE THREAD

**Issue by gs11** [gravitee-io/issues#1591]
### Expected Behavior
I assume the following should be valid (see configuration below)
* Settings -> Users should display a + to add users
* Sign-up option should be available on the login page
* Users list should include all users in the gravitee.yml file

### Current Behavior
* No + icon is visible in the users list
* No Sign-up option visible on login page
* No users other than "admin" is visible in the Users list

### Steps to Reproduce (for bugs)
1. Install the latest version of the helm chart - https://github.com/gravitee-io/gravitee-kubernetes
2. Edit the configmap so that user / creation / enabled: true in gravitee.yml
3. Restart the pod to ensure the updated configmap is read
4. Verify the gravitee.yml content in the pod container

### Context
I'd like to be able to add users other than admin

### Your Environment
* Version used: 1.15
* Browser Name and version: Firefox 62
* Operating System and version: Windows 10

**Comment by brasseld** [comment]
https://github.com/gravitee-io/issues/issues/1505

**Comment by gs11** [comment]
Thanks @brasseld but neither the users in gravitee.yml are visible nor the sign-up link on the login page. I guess those should be working based on the current configuration?

**Comment by gs11** [comment]
The full context of the config is:
```
user:
   login:
      # Create a default application when user connects to the portal for the very first time (default true)
      #defaultApplication: true
   creation:
      # Allows to register new users from portal (default false)
      enabled: true
      token:
         #expire-after: 86400
```
