### ISSUE TITLE
[gateway] Prometheus unable to scrape metrics from API Gateway

### ISSUE THREAD

**Issue by Dwaipayana23** [gravitee-io/issues#1874]
I'd configured Prometheus with Gravitee API Gateway for the former to scrape metrics from the latter. 
- `services.core.http` and `services.metrics` configuration in the `gravity.yml` file of the gateway:

```yaml
services:
  core:
    http:
      enabled: true
      port: 18082
      host: localhost
      authentication:
        # authentication type to be used for the core services
        # - none : to disable authentication
        # - basic : to use basic authentication
        # default is "basic"
        type: basic
        users:
          admin: adminadmin
  [...]
  # metrics service
  metrics:
    enabled: true
    prometheus:
      enabled: true

```

- `scrape_config` part of the `prometheus.yml` file:

```yaml
scrape_configs:
  - job_name: 'fabric_gravitee'
    basic_auth:
      username: admin
      password: adminadmin
    metrics_path: /_node/metrics/prometheus
    static_configs:
      - targets: ['host-mac-ip:18082']

```
I assume port `18082` used in Prometheus configuration file is indeed the port where the `http` service is exposed from Gravitee.

### Expected Behavior
The target `fabric_gravitee` should be _healthy_ and Prometheus should produce and display time series objects corresponding to the metrics captured from Gravitee.

### Current Behavior
The target `fabric_gravitee` is `DOWN` and the following reason is stated in Prometheus Management UI:

| Endpoint                                           | State  | Labels                                              | Last Scrape | Scrape Duration | Error                                                                                                                                   |
|----------------------------------------------------|--------|-----------------------------------------------------|-------------|-----------------|-----------------------------------------------------------------------------------------------------------------------------------------|
| http://host-mac-ip:18082/_node/metrics/prometheus | `DOWN` | instance="172.30.5.167:18082" job="fabric_gravitee" | 40.212s ago | 761.7us         | `Get http://host-mac-ip:18082/_node/metrics/prometheus: read tcp 172.17.0.6:50882->host-mac-ip:18082: read: connection reset by peer` |

### Possible Solution
I have my doubts on the correctness two specific parameters in the `prometheus.yml` config file:
- the port specified at `scrape_configs.static_configs.targets` as `18082`, as in the `service.http` port specified in `gravitee.yml` file: **is the port right**?
- the path where metrics are exposed: `/_node/metrics.prometheus`: **is the path right**?

### Steps to Reproduce (for bugs)

1. Have running instance of Prometheus and Gravitee Gatway API  
2. Add the `metrics` configuration under the `services` key in the `gravitee.yml` file (as specified above).
3. Add the `scrape_config` for the Gravitee API Gateway in `prometheus.yml` config file.
4. Reload the Gravitee Gateway by running `gravitee` and reload the Prometheus server by sending a `/_/reload` `POST` request to the server.
5. Check the status of the target (for which the `scrape_config` was updated) in the Prometheus UI (default path: http://host-mac-ip:9090/targets)

### Context

At present, I see only those time series objects that Prometheus generates by default and I do not see any target-specific metric.

### Your Environment

* Version used: `1.21.2`
* Browser Name and version: Google Chrome (71.0.3578.98, 64bit)
* Operating System and version: Gravitee and Prometheus are running off an Ubuntu Server 16.04.4 LTS; browser is in Windows 10
