### ISSUE TITLE
use env var in gravitee.yml

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2]
gravitee.yml (on gateway and management-api) contains an hard coded port and host for datasource 
```
ds:
  mongodb:
    dbname: gravitee
    host: localhost
    port: 27017
  elastic:
    host: localhost
    port: 9300
```

because we use this file in our docker environment, we have to modify it with `sed` command to change `localhost` with the docker container which is running ES or mongo.

It could be very convenient if gravitee.yml accepts env variable for this configuration.

**Comment by brasseld** [comment]
Hello @NicolasGeraud,

You can use environment variables in _gravitee.yml_ by using the following syntax:
```
ds:
  mongodb:
    dbname: gravitee
    host: ${mongo_host}
    port: ${mongo_port}
```

And in your shell:
```
> export mongo_host=localhost
> export mongo_port=27017
```

Enjoy !

**Comment by NicolasGeraud** [comment]
Is there a way to provide default value ?
Somethig like
```
ds:
  mongodb:
    dbname: gravitee
    host: ${mongo_host | localhost}
    port: ${mongo_port | 27017}
```

**Comment by brasseld** [comment]
Sure you can !

```
ds:
  mongodb:
    dbname: gravitee
    host: ${systemProperties['mongo_host']:localhost}
    port: 27017
```
