### ISSUE TITLE
default-idp-admin force de default mondo uri

### ISSUE THREAD

**Issue by mielune** [gravitee-io/issues#2055]
Creating an AM using the next ds details:

AM Release 2.3.0

```yaml
ds:
  mongodb:
    dbname: gravitee
    host: 192.168.0.123
    port: 27017
    username: gravitee
    password: "xxxxxxxxxxxx"
    authSource: admin
```

The created `default-idp-admin` has the next details in the management database:

```json
{
 "_id" : "default-idp-admin", 
"configuration" : "{
\"uri\":\"mongodb://localhost:27017\",
\"host\":\"192.168.0.123\",
\"port\":27017,
\"enableCredentials\":false,\"database\":\"gravitee\",\"usersCollection\":\"idp_users_admin\",\"findUserByUsernameQuery\":\"{username: ?}\",\"usernameField\":\"username\",\"passwordField\":\"password\",\"passwordEncoder\":\"BCrypt\"}", "createdAt" : ISODate("2019-03-18T13:38:53.604Z"), "domain" : "admin", "external" : false, "mappers" : {  }, 
"name" : "Default Identity Provider", 
"roleMapper" : {  }, 
"type" : "mongo-am-idp", 
"updatedAt" : ISODate("2019-03-18T13:38:53.604Z") }
```

You can see that the `uri` parameter is setup by default without using the `host` and `port` fields:
-"uri":"mongodb://localhost:27017",
-"host":"192.168.0.123",
-"port":27017,
