### ISSUE TITLE
[management-api] Normalize Elasticsearch configuration

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#212]
The way to configure Elasticsearch is not the same between the gateway and the management-rest-api. It would be really great to keep an homogeneous configuration.

Gateway:
```yaml
  elasticsearch:
    enabled: true # Is the reporter enabled or not (default to true)
    hosts:
      - ${ds.elastic.host}:${ds.elastic.port}
    cluster: gravitee
    index: gravitee
    bulk:
      actions: 1000           # Number of requests action before flush
      flush_interval: 5       # Flush interval in seconds
      concurrent_requests: 5  # Concurrent requests
```

Management API:
```yaml
  elasticsearch:
    hosts:
      - ${ds.elastic.host}:${ds.elastic.port}
    index:
      name: gravitee
    cluster:
      name: gravitee
```
