### ISSUE TITLE
[gravitee-io/gravitee-kubernetes] configuration error

### ISSUE THREAD

**Issue by zhoumingjun** [gravitee-io/issues#2128]
https://github.com/gravitee-io/gravitee-kubernetes/blob/master/gravitee/templates/api-configmap.yaml

Currently it is 
```yml
    services:
      core:
      http:
        enabled: true
        port: 18083
        host: localhost
        authentication:
          type: basic
          users:
            admin: adminadmin
```

It should be 
```yml
    services:
      core:
        http:
          enabled: true
          port: 18083
          host: localhost
          authentication:
            type: basic
            users:
              admin: adminadmin
```
