### ISSUE TITLE
graviteeio/am-management-ui:2.5.0 [security] CVE-2019-11068

### ISSUE THREAD

**Issue by mielune** [gravitee-io/issues#2267]
Using the last release of AM's Docker Image 2.5.0, this CVE is raised.

### Expected Behavior

With previous 2.4.0, no CVE raised by the docker images.

### Current Behavior

Our CI pipeline raised this CVE:

```
2019/05/20 13:44:34 [ERRO] ▶ Image [graviteeio/am-management-ui:2.5.0] contains 1 unapproved vulnerabilities
+------------+---------------------+--------------+-----------------+---------------------------------------------------------------+
| STATUS     | CVE SEVERITY        | PACKAGE NAME | PACKAGE VERSION | CVE DESCRIPTION                                               |
+------------+---------------------+--------------+-----------------+---------------------------------------------------------------+
| Unapproved | High CVE-2019-11068 | libxslt      | 1.1.32-r0       |                                                               |
|            |                     |              |                 | https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11068 |
+------------+---------------------+--------------+-----------------+---------------------------------------------------------------+
```

### Steps to Reproduce (for bugs)

1. Build an image based on graviteeio/am-management-ui:2.5.0
2. Run a security scan on the built image

### Context

Upgraing from 2.4.0 to 2.5.0

### Your Environment

* Version used: 2.5.0
* Browser Name and version: N/A
* Operating System and version: Docker

**Comment by tcompiegne** [comment]
Hi @mielune,

Are you sure is for the AM project ?

I can't find the `libxslt` in the AM UI NPM  dependency tree ... weird.

**Comment by mielune** [comment]
Hi @tcompiegne 

I'm using this service description in my swarm docker-compose.yml;

```yaml
  management-ui:
    image: 'graviteeio/am-management-ui:${GRAVITEE_AM_VERSION}'
    networks:
    - 'proxy'
    environment:
    - 'MGMT_API_URL=http://${GRAVITEE_AM_MNGT}/'
    - 'MGMT_UI_URL=http://${GRAVITEE_AM_ADMIN}/'
    - 'SERVICE_PORTS=80'
    - 'VIRTUAL_HOST=http://${GRAVITEE_AM_ADMIN}/*'
    - 'VIRTUAL_HOST_WEIGHT=0'
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        window: 10s
```

With GRAVITEE_AM_VERSION=2.5.0 in the CI script.
I'm using `arminc/clair-local-scan:v2.0.4` for the security scan.
