### ISSUE TITLE
[management] overwrite in memory users properties using environment variable

### ISSUE THREAD

**Issue by ADefossez-Zenika** [gravitee-io/issues#2490]
### Expected Behavior

We should be able to create user in memory (for administration purposes) and overwrite existing users properties (such as password), providing environment variables at runtime. 

### Current Behavior

when launching gravitee api-management with environment variables to overwrite 'in memory' users, changes never happend.

### Steps to Reproduce (for bugs)

using your docker-compose files, i add environnement variables on the management-api service. Cf Context part, bellow.

### Context

Using this part of gravitee.yml:

``` yaml
security:
  # When using an authentication providers, use trustAll mode for TLS connections
  # trustAll: false
  providers:  # authentication providers
    - type: memory
      password-encoding-algo: bcrypt
      users:
        - user:
          username: admin
          # Password value: admin
          password: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
          roles: MANAGEMENT:ADMIN, PORTAL:ADMIN
        - user:
          username: user2
          # Password value: api1
          password: $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji
          # You can declare multiple roles using comma separator
          roles: MANAGEMENT:ADMIN, PORTAL:ADMIN
```

launching gravitee as containers, i try to overwrite users properties, using environment :

Source : <https://docs.gravitee.io/apim_installguide_docker.html#docker_compose>

file: docker-compose-local.yml
``` yaml
    environment:
      - "gravitee_management_mongodb_uri=mongodb://demo-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000" 
      - "gravitee_analytics_elasticsearch_endpoints_0=http://demo-elasticsearch:9200" 
      - "gravitee_security_providers_0_users_1_password=$$2a$$10$$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq" #admin
      - "gravitee_security_providers_0_users_1_roles=MANAGEMENT:ADMIN, PORTAL:ADMIN"
      - "gravitee_security_providers_0_users_1_username=test"
```

I've logged into my management-api container, and launch an export of environment variables, here is what i've got.

``` bash
/opt/graviteeio-management-api/logs # export
export GRAVITEEIO_HOME='/opt/graviteeio-management-api'
export HOME='/root'
export HOSTNAME='demo-managementapi'
export JAVA_ALPINE_VERSION='8.181.13-r0'
export JAVA_HOME='/usr/lib/jvm/java-1.8-openjdk/jre'
export JAVA_VERSION='8u181'
export LANG='C.UTF-8'
export OLDPWD='/opt/graviteeio-management-api'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin'
export PWD='/opt/graviteeio-management-api/logs'
export SHLVL='1'
export TERM='xterm'
export gravitee_analytics_elasticsearch_endpoints_0='http://demo-elasticsearch:9200'
export gravitee_management_mongodb_uri='mongodb://demo-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000'
export gravitee_security_providers_0_users_1_password='$2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq'
export gravitee_security_providers_0_users_1_roles='MANAGEMENT:ADMIN, PORTAL:ADMIN'
export gravitee_security_providers_0_users_1_username='test'
```

### Your Environment

* Version used: 1.28
