### ISSUE TITLE
Management UI not able to reach the management API container

### ISSUE THREAD

**Issue by CDPrete** [gravitee-io/issues#2518]
Hi all!
I'm trying to deploy the trio API-UI-Gateway in our Docker environment, but at the moment the UI is not able to reach the API container.
As "guide" I'm actually following there resources:

- https://github.com/gravitee-io/gravitee-docker/tree/master/environments/demo
- https://docs.gravitee.io/apim_installguide_docker.html

This is the manifest for my docker-compose (the important parts):
```
gravitee-management-api:
        image: graviteeio/management-api:1.28.0
        container_name: gravitee-management-api
        ports:
          - "8005:8083"
        depends_on:
          - elasticsearch
          - mongodb
        environment:
          gravitee_analytics_elasticsearch_endpoints_0: "http://elasticsearch:9200"
          GRAVITEE_MANAGEMENT_MONGODB_URI: "mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"

    gravitee-management-ui:
        image: graviteeio/management-ui:1.28.0
        container_name: gravitee-management-ui
        ports:
          - "8002:80"
        depends_on:
          - gravitee-management-api
        environment:
          MGMT_API_URL: "http://localhost:8005/management/"

    gravitee-management-gateway:
        image: graviteeio/gateway:1.28.0
        container_name: gravitee-management-gateway
        ports:
          - "8000:8082"
        depends_on:
          - elasticsearch
          - mongodb
        environment:
          GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0: "http://elasticsearch:9200"
          GRAVITEE_MANAGEMENT_MONGODB_URI: "mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
          GRAVITEE_RATELIMIT_MONGODB_URI: "mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        container_name: elasticsearch

    mongodb:
        image: mongo:3.4
        container_name: mongodb
```

According to the installation guide, everything should be fine, but when I try to call `http://localhost:8002` from Chrome I get a page with the message "Management API unreachable or error occurs, please check logs" and in the console logs I have

```
vendors~app~vendor-feb7128bcfe2235cc811.js:117 WARNING: Tried to load AngularJS more than once.
vendors~app~vendor-feb7128bcfe2235cc811.js:117 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://localhost:8005/management/portal","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"}
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
c @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
$digest @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
$apply @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
M @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
_.onerror @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
error (async)
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
$digest @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
$apply @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
M @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
_.onload @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
load (async)
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
$digest @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
h @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
setTimeout (async)
i.defer @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
$evalAsync @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
d @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
then @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
_ @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
_.<computed> @ vendors~app~vendor-feb7128bcfe2235cc811.js:117
(anonymous) @ app-feb7128bcfe2235cc811.js:1
r @ app-feb7128bcfe2235cc811.js:1
i @ app-feb7128bcfe2235cc811.js:1
(anonymous) @ app-feb7128bcfe2235cc811.js:1
(anonymous) @ app-feb7128bcfe2235cc811.js:1
vendors~app~vendor-feb7128bcfe2235cc811.js:117 GET http://localhost:8005/management/portal net::ERR_EMPTY_RESPONSE
```

Do you have any idea what I'm missing?

Thanks and regards,
- cdprete
