### ISSUE TITLE
[management][reporters] default reporter configuration must handle MongoDB cluster configuration

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#2527]
Currently to create the default domain's reporter, we use this configuration : 

```
String mongoHost = environment.getProperty("management.mongodb.host", "localhost");
String mongoPort =  environment.getProperty("management.mongodb.port", "27017");
String mongoDBName = environment.getProperty("management.mongodb.dbname", "gravitee-am");
String mongoUri = environment.getProperty("management.mongodb.uri", "mongodb://"+ mongoHost + ":" + mongoPort + "/" + mongoDBName);
```
We must handle this kind of configuration : 

```
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
```

**Comment by lazki** [comment]
A workaround:
Instead of using servers:, you can use the URI form, and it works.
```yaml
management:
  type: mongodb
  mongodb:
    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```

Note: configure username and password only once.
