### ISSUE TITLE
[management] Gravitee docker compose file ldap role mapping help 

### ISSUE THREAD

**Issue by SteffenTIK** [gravitee-io/issues#2673]
### Expected Behavior
Automatic assignment of LDAP user groups members to the Gravitee roles.

### Current Behavior

Members of the LDAP group "GRAVITEE_ADMINS" have the role "[MANAGEMENT] USER" and
"[PORTAL] USER" after logging in to the Gravitee management but they should be the role "[MANAGEMENT] ADMIN" and
"[PORTAL] ADMIN".

### Possible Solution

Incorrect syntax for the group/role mapping in my docker-compose.yml file.

### Steps to Reproduce (for bugs)

1. Current role definition in my docker-compose.yml file
"- gravitee_security_providers_1_authentication_group_filter=member={0}"
"- gravitee_security_providers_1_authentication_group_base=OU=APIGW,OU=BerechtigungsGruppen"
"- gravitee_security_providers_1_authentication_group_role_attribute=cn"
"- gravitee_security_providers_1_authentication_group_role_mapper={GRAVITEE_ADMINS:ADMIN, GRAVITEE_USERS:USER, GRAVITEE_PUBLISHERS:API_PUBLISHER, GRAVITEE_CONSUMERS:API_CONSUMER}"

### Your Environment

* Version used: 1.28.0
* Browser Name and version: Chromium 76
* Docker Image: graviteeio/management-api:latest

**Comment by brasseld** [comment]
Hi @SteffenTIK 

Thanks for creating the issue.

Can you have a try to format the exact content of your `docker-compose.yml` because I've not sure about the syntax you've tried.

You should use this kind of syntax:

\```yaml

// put your content here

\```

Thanks

**Comment by SteffenTIK** [comment]
Hi @brasseld,

here is a part of my configuration:

```yaml

server-api-sv04:
    hostname: server-api-sv04.company.intern
    image: 'graviteeio/management-api:latest'
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
      - JAVA_OPTS=-Djavax.net.debug=all           
      - gravitee_security_providers_1_type=ldap
      - gravitee_security_providers_1_context_username=CN=APIGateway01,OU=Service,dc=company,dc=intern
      - gravitee_security_providers_1_context_password=Password
      - gravitee_security_providers_1_context_url=ldap://server-ldap-sv01.company.intern:389
      - gravitee_security_providers_1_context_base=dc=company,dc=intern
      - gravitee_security_providers_1_authentication_user_base= 
      - gravitee_security_providers_1_authentication_user_filter=(&(objectCategory=person)(sAMAccountName={0})(memberOf=cn=GRAVITEE_ACCESS,ou=APIGW,ou=BerechtigungsGruppen,dc=company,dc=intern))
      - gravitee_security_providers_1_authentication_group_base=OU=APIGW,OU=BerechtigungsGruppen
      - gravitee_security_providers_1_authentication_group_filter=member={0}
      - gravitee_security_providers_1_authentication_group_role_attribute=cn
      - gravitee_security_providers_1_authentication_group_role_mapper={GRAVITEE_ADMINS:ADMIN, GRAVITEE_USERS:USER, GRAVITEE_PUBLISHERS:API_PUBLISHER, GRAVITEE_CONSUMERS:API_CONSUMER}
      - gravitee_security_providers_1_lookup_user_base=
      - gravitee_security_providers_1_lookup_user_filter=(&(objectCategory=person)(cn=*{0}*))
    ports:
      - "8005:8083"    
    depends_on:
      - mongodb
      - elasticsearch

```

**Comment by brasseld** [comment]
Ok, did you try something like this:

```yaml
server-api-sv04:
    hostname: server-api-sv04.company.intern
    image: 'graviteeio/management-api:latest'
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
      - JAVA_OPTS=-Djavax.net.debug=all           
      - gravitee_security_providers_1_type=ldap
      - gravitee_security_providers_1_context_username=CN=APIGateway01,OU=Service,dc=company,dc=intern
      - gravitee_security_providers_1_context_password=Password
      - gravitee_security_providers_1_context_url=ldap://server-ldap-sv01.company.intern:389
      - gravitee_security_providers_1_context_base=dc=company,dc=intern
      - gravitee_security_providers_1_authentication_user_base= 
      - gravitee_security_providers_1_authentication_user_filter=(&(objectCategory=person)(sAMAccountName={0})(memberOf=cn=GRAVITEE_ACCESS,ou=APIGW,ou=BerechtigungsGruppen,dc=company,dc=intern))
      - gravitee_security_providers_1_authentication_group_base=OU=APIGW,OU=BerechtigungsGruppen
      - gravitee_security_providers_1_authentication_group_filter=member={0}
      - gravitee_security_providers_1_authentication_group_role_attribute=cn
      - gravitee_security_providers_1_authentication_group_role_mapper_GRAVITEE_ADMINS=ADMIN
      - gravitee_security_providers_1_authentication_group_role_mapper_GRAVITEE_USERS=USER      
      - gravitee_security_providers_1_authentication_group_role_mapper_GRAVITEE_CONSUMERS=API_CONSUMER
      - gravitee_security_providers_1_lookup_user_base=
      - gravitee_security_providers_1_lookup_user_filter=(&(objectCategory=person)(cn=*{0}*))
```
