### ISSUE TITLE
Send error for wrong subpath

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#3001]
I have API with only 2 subpaths (even without root path (/), beacuse this API has no logic for the root url) and for requests to `/contextpath/wrongsubpath` I expected HTTP-404 error, but my requests goes to the back-service without any errors. 

Here the example of my API:
```yaml
{
  "name": "Messenger",
  "version": "1.0.0",
  "description": "Test",
  "visibility": "PRIVATE",
  "paths": {
    "/sendText": [],
    "/getUpdates": []
  },
  "resources": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "65505156-77a7-4a76-9051-5677a79a765c",
      "name": "Plan",
      "description": "Plan",
      "validation": "AUTO",
      "security": "KEY_LESS",
      "securityDefinition": "{}",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "55e17aca-6546-4034-a17a-ca6546103484"
      ],
      "order": 1,
      "characteristics": [],
      "created_at": 1574349744922,
      "updated_at": 1576070223074,
      "published_at": 1574349750577,
      "paths": {
        "/": []
      },
      "excluded_groups": [],
      "comment_required": false
    }
  ],
  "path_mappings": [],
  "proxy": {
    "virtual_hosts": [
      {
        "path": "/messenger/v1"
      }
    ],
    "strip_context_path": false,
    "preserve_host": false,
    "logging": {
      "mode": "CLIENT_PROXY",
      "condition": "true"
    },
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "http://localhost:8089/messenger/v1",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "inherit": true
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false,
          "encodeURI": false
        }
      }
    ]
  },
  "response_templates": {}
}
```

### Your Environment
* Version used: 1.30.0
