### ISSUE TITLE
[helm] chart does not allow to modify the header / query param for the API Key

### ISSUE THREAD

**Issue by JulienFauvel** [gravitee-io/issues#3225]
The chart should allow the customization of the API key header

In the gateway's gravitee.yml
```
policy:
# Customize the api-key header and / or query parameter.
# Set an empty value to prohibit its use.
  api-key:
    header: X-Gravitee-Api-Key
    param: api-key
```
