### ISSUE TITLE
gravitee.yml Identity provider not set up

### ISSUE THREAD

**Issue by TimothyFehr** [gravitee-io/issues#3249]
I try to set up KeyCloak as the identety provider for gravitee. so it can be used in our dockerized environment. To check if it is a valid solution, i tested a manual setup on my local machine which worked like a charm. But when i now try to switch over to a more automated setup, using the gravitee.yml file it fails completely.

### Expected Behavior
The expected behaviour would be that the identety provider is set up (if not functioning ok, but at least visible in the Settings)

### Current Behavior
No identety provider is set up at all

### Steps to Reproduce (for bugs)
1. setup / start a keycloak ( use docker for that ) by following your tutorial to set the realm and user
2. edit the gravitee.yml to point to the keycloak
3. start the dockerized gravitee environment (yours)
4. Try to login with the new identety  provider
5. check if there is a identety  provider parcially setup in the settings

### Your Environment
managementui:
    image: graviteeio/management-ui:latest

managementapi:
    image: graviteeio/management-api:latest

portalui:
    image: graviteeio/portal-ui:nightly

portalapi:
    image: graviteeio/portal-api:nightly

* Browser Name and version:
Chrom Version 79.0.3945.130
Firefox 68.4.1esr

* Operating System and version:
Windows 10

**Comment by aelamrani** [comment]
Any log to share?

**Comment by TimothyFehr** [comment]
Shure, from which component do you need to have the logs exactly? (in your docker setup 5 containers are needed to run gravitee)

My gues would be the following two?
[LocalManagementAPILog.txt](https://github.com/gravitee-io/issues/files/4243456/LocalManagementAPILog.txt)
[LocalGatewayLog.txt](https://github.com/gravitee-io/issues/files/4243451/LocalGatewayLog.txt)

**Comment by aelamrani** [comment]
Thank you.

It seems there is no identity provider defined in your configuration. Can you please check, or share it.

**Comment by TimothyFehr** [comment]
i defined it as described in your documentation 
```yaml 
security:
  # When using an authentication providers, use trustAll mode for TLS connections
  # trustAll: false
  providers:  # authentication providers
    providers:
      - type: oidc
        id: keycloak # not required if not present, the type is used
        clientId: gravitee
        clientSecret: 46f57aac-de18-43ef-a8e9-f7209fa42fac
        tokenIntrospectionEndpoint: "http://172.21.113.61:8080/auth/realms/master/protocol/openid-connect/token/introspect"
        tokenEndpoint: "http://172.21.113.61:8080/auth/realms/master/protocol/openid-connect/token"
        authorizeEndpoint: "http://172.21.113.61:8080/auth/realms/master/protocol/openid-connect/auth"
        userInfoEndpoint: "http://172.21.113.61:8080/auth/realms/master/protocol/openid-connect/userinfo"
        userLogoutEndpoint: "http://172.21.113.61:8080/auth/realms/master/protocol/openid-connect/logout?redirect_uri="
        color: "#0076b4"
        scopes:
          - openid
          - mmail
        userMapping:
          id: sub
          email: email
          lastname: family_name
          firstname: given_name
          picture: picture
        groupMapping:
          - condition: "{#jsonPath(#profile, '$.identity_provider_id') == 'PARTNERS' && #jsonPath(#profile, '$.job_id') != 'API_MANAGER'}"
            groups:
              - Group 1
              - Group 2
        roleMapping:
          - condition: "{#jsonPath(#profile, '$.job_id') != 'API_MANAGER'}"
            roles:
              - "PORTAL:PARTNER"
              - "MANAGEMENT:API_CONSUMER"
```

**Comment by aelamrani** [comment]
Ok thank you, i will have a try later

**Comment by TimothyFehr** [comment]
thanks for your help
let me know if i can help out with more information

**Comment by aelamrani** [comment]
It seems there is a mistake on your pasted configuration, you have defined `providers` twice.

**Comment by TimothyFehr** [comment]
Removed it and corrected a typo in the scopes still acting the same way

this is my full yaml myabe it helps:
``` YAML
############################################################################################################
################################ Gravitee.IO Management API - Configuration ################################
############################################################################################################

############################################################################################################
# This file is the general configuration of Gravitee.IO Management API:
# - Properties (and respective default values) in comment are provided for information.
# - You can reference other property by using ${property.name} syntax
# - gravitee.home property is automatically set-up by launcher and refers to the installation path. Do not override it !
#
# Please have a look to http://docs.gravitee.io/ for more options and fine-grained granularity
############################################################################################################

# HTTP Server
#jetty:
#  IP/hostname to bind to. Default is 0.0.0.0
#  host: 0.0.0.0
#  port: 8083
#  idleTimeout: 30000
#  acceptors: -1
#  selectors: -1
#  pool:
#    minThreads: 10
#    maxThreads: 200
#    idleTimeout: 60000
#    queueSize: 6000
#  jmx: false
#  statistics: false
#  accesslog:
#    enabled: true
#    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log
#  secured: false
#  ssl:
#    keystore:
#      type: jks # Supports jks, pkcs12
#      path: ${gravitee.home}/security/keystore.jks
#      password: secret
#    truststore:
#      type: jks # Supports jks, pkcs12
#      path: ${gravitee.home}/security/truststore.jks
#      password: secret

http:
  api:
    # Configure the listening path for the API. Default to /management
    #entrypoint: /management
  cors:
    # Allows to configure the header Access-Control-Allow-Origin (default value: *)
    # '*' is a valid value but is considered as a security risk as it will be opened to cross origin requests from anywhere.
    #allow-origin: http://developer.mycompany.com
    # Allows to define how long the result of the preflight request should be cached for (default value; 1728000 [20 days])
    #max-age: 864000
    # Which methods to allow (default value: OPTIONS, GET, POST, PUT, DELETE)
    #allow-methods: 'OPTIONS, GET, POST, PUT, DELETE'
    # Which headers to allow (default values: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With, If-Match)
    #allow-headers: 'X-Requested-With'
  hsts:
    enabled: true
    include-sub-domains: true
    max-age: 31536000

# Plugins repository
#plugins:
#  path:
#    - ${gravitee.home}/plugins
#    - ${gravitee.home}/my-custom-plugins
# If a external is already installed (but with a different version), management node does not start anymore
#  failOnDuplicate: true

# Management repository is used to store global configuration such as APIs, applications, apikeys, ...
# This is the default configuration using MongoDB (single server)
# For more information about MongoDB configuration, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true
# possible values are 1,2,3... (the number of node) or 'majority'
#    writeConcern: 1
#    wtimeout: 0
#    journal: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250

services:
  core:
    http:
      enabled: true
      port: 18083
      host: localhost
      authentication:
        # authentication type to be used for the core services
        # - none : to disable authentication
        # - basic : to use basic authentication
        # default is "basic"
        type: basic
        users:
          admin: adminadmin

  # metrics service
  metrics:
    enabled: false
    prometheus:
      enabled: true

# Analytics repository is used to store all reporting, metrics, health-checks stored by gateway instances
# This is the default configuration using Elasticsearch
analytics:
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://${ds.elastic.host}:${ds.elastic.port}
#    index: gravitee
#    index_per_type: true
#    cross_cluster:
#      mapping:
#        tenant_id: cluster_name
#        tenant_id: cluster_name
#    security:
#      username: user
#      password: secret
#    http:
#      timeout: 10000 # in milliseconds
#

# Authentication and identity sources
# Users can have following roles (authorities):
#  USER: Can access portal and be a member of an API
#  API_PUBLISHER: Can create and manage APIs
#  API_CONSUMER: Can create and manage Applications
#  ADMIN: Can manage global system
security:
  # When using an authentication providers, use trustAll mode for TLS connections
  # trustAll: false
  providers:  # authentication providers
    - type: oidc
      id: keycloak # not required if not present, the type is used
      clientId: gravitee
      clientSecret: 46f57aac-de18-43ef-a8e9-f7209fa42fac
      tokenIntrospectionEndpoint: "http://http://devportal.t3.devops.f4o.ch:8080/auth/realms/master/protocol/openid-connect/token/introspect"
      tokenEndpoint: "http://http://devportal.t3.devops.f4o.ch:8080/auth/realms/master/protocol/openid-connect/token"
      authorizeEndpoint: "http://http://devportal.t3.devops.f4o.ch:8080/auth/realms/master/protocol/openid-connect/auth"
      userInfoEndpoint: "http://http://devportal.t3.devops.f4o.ch:8080/auth/realms/master/protocol/openid-connect/userinfo"
      userLogoutEndpoint: "http://http://devportal.t3.devops.f4o.ch:8080/auth/realms/master/protocol/openid-connect/logout?redirect_uri="
      color: "#0076b4"
      scopes:
        - openid
        - email
      userMapping:
        id: sub
        email: email
        lastname: family_name
        firstname: given_name
        picture: picture
      groupMapping:
        - condition: "{#jsonPath(#profile, '$.identity_provider_id') == 'PARTNERS' && #jsonPath(#profile, '$.job_id') != 'API_MANAGER'}"
          groups:
            - Group 1
            - Group 2
      roleMapping:
        - condition: "{#jsonPath(#profile, '$.job_id') != 'API_MANAGER'}"
          roles:
            - "PORTAL:PARTNER"
            - "MANAGEMENT:API_CONSUMER"

# SMTP configuration used to send mails
email:
  enabled: true
  host: mail.olymp
  subject: "[Gravitee.io] %s"
  port: 25
  from: noreply@devportal.t3.devops.f4o.ch
  username: 
  password: 
#  properties:
#    auth: true
#    starttls.enable: true
#    ssl.trust: smtp.gmail.com

# Mail templates
#templates:
#  path: ${gravitee.home}/templates

# Referenced properties
ds:
  mongodb:
    dbname: gravitee
    host: localhost
    port: 27017
  elastic:
    host: localhost
    port: 9200

jwt:
  secret: myJWT4Gr4v1t33_S3cr3t
  # Allows to define the end of validity of the token in seconds (default 604800 = a week)
  #expire-after: 604800
  # Allows to define the end of validity of the token in seconds for email registration (default 86400 = a day)
  #email-registration-expire-after: 86400
  # Allows to define issuer (default gravitee-management-auth)
  #issuer: gravitee-management-auth
  # Allows to define cookie context path (default /)
  #cookie-path: /
  # Allows to define cookie domain (default "")
  #cookie-domain: .gravitee.io
  # Allows to define if cookie secure only (default false)
  #cookie-secure: true

swagger:
  # Default scheme used when creating an API from a Swagger descriptor if there is no scheme specified.
  scheme: https

user:
  login:
    # Create a default application when user connects to the portal for the very first time (default true)
    #defaultApplication: true
  creation:
    token:
      #expire-after: 86400
  reference:
      # Secret key used to generate reference of a user which is unique (default: s3cR3t4grAv1t33.1Ous3D4R3f3r3nc3)
      # Must contains 32 chars (256 bits)
      #secret:
  anonymize-on-delete:
    #enabled: true

# The portal URL used in emails
portalURL: http://localhost:3000/

search:
  data: ${gravitee.home}/data

# global configuration of the http client
#httpClient:
#  timeout: 10000 # in milliseconds
#  proxy:
#    type: HTML #HTTP, SOCK4, SOCK5
#    http:
#      host: localhost
#      port: 3128
#      username: user
#      password: secret
#    https:
#      host: localhost
#      port: 3128
#      username: user
#      password: secret

notifiers:
  email:
    enabled: true
    host: ${email.host}
    subject: ${email.subject}
    port: ${email.port}
    from: ${email.from}
    username: ${email.username}
    password: ${email.password}
#    starttls.enabled: false
#    ssl:
#      trustAll: false
#      keyStore:
#      keyStorePassword:

```

**Comment by aelamrani** [comment]
Everything seems correct, please share logs of the management API part.

**Comment by TimothyFehr** [comment]
just missed, I added some logs above

**Comment by aelamrani** [comment]
According to the logs, the configuration does not seem to be taken into account. Did you configure env vars on security providers? Can you try to restart again and share logs?

**Comment by TimothyFehr** [comment]
I have no env vars which have something todo with the security provider (which i am aware of) i hardcoded them all in the config yaml. (to make shure)

i allways stop and prune:
[LocalManagementAPILog.txt](https://github.com/gravitee-io/issues/files/4245826/LocalManagementAPILog.txt)
[LocalGatewayLog.txt](https://github.com/gravitee-io/issues/files/4245827/LocalGatewayLog.txt)

**Comment by aelamrani** [comment]
Hmmm weird, i just had a check locally and no problem at all...

<img width="393" alt="Capture d’écran 2020-02-24 à 18 35 35" src="https://user-images.githubusercontent.com/1580262/75176548-a5374480-5734-11ea-99bc-73afb3668168.png">

I will do a deeper analysis later and keep you informed. If in the meantime you think of something that will allow me to reproduce easily, do not hesitate.

**Comment by TimothyFehr** [comment]
can you provide your yaml? so i can compare?

**Comment by aelamrani** [comment]
I used the yours and i can see these logs:

```
08:56:12.722 [graviteeio-node] INFO  i.g.m.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.management.service.impl.upgrade.IdentityProviderUpgrader
08:56:12.722 [graviteeio-node] INFO  i.g.m.s.i.u.IdentityProviderUpgrader - Upsert identity provider config [oidc]
```

**Comment by TimothyFehr** [comment]
can you share your docker compose? i feel that we may have a version mis match

**Comment by aelamrani** [comment]
Sure, here it is: 

```YAML
version: '2'

volumes:
  datamongo: {}
  dataelasticsearch: {}

services:
  elasticsearch:
    hostname: demo-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - dataelasticsearch:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/var/log/elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536

  mongodb:
    hostname: demo-mongodb
    image: mongo:4.0.14
    volumes:
      - datamongo:/data/db
      - ./logs/mongodb:/var/log/mongodb

  gateway:
    hostname: demo-gateway
    image: graviteeio/gateway:latest
    links:
      - "mongodb:demo-mongodb"
      - "elasticsearch:demo-elasticsearch"
    ports:
      - "8000:8082"
    volumes:
      - ./logs/gateway:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://demo-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://demo-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://demo-elasticsearch:9200

  managementui:
    hostname: demo-managementui
    image: graviteeio/management-ui:latest
    ports:
      - "8002:80"
    volumes:
      - ./logs/management-ui:/var/log/httpd
    environment:
      - MGMT_API_URL=http:\/\/localhost:8005\/management\/

  managementapi:
    hostname: demo-managementapi
    image: graviteeio/management-api:latest
    ports:
      - "8005:8083"
    volumes:
      - ./logs/management-api:/home/gravitee/logs
      - ./gravitee.yml:/opt/graviteeio-management-api/config/gravitee.yml
    links:
      - "mongodb:demo-mongodb"
      - "elasticsearch:demo-elasticsearch"
    environment:
      - gravitee_management_mongodb_uri=mongodb://demo-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://demo-elasticsearch:9200
```
