### ISSUE TITLE
[management] Default admin can't go to the dashboard and settings menu

### ISSUE THREAD

**Issue by bat79a** [gravitee-io/issues#3834]
In a fresh install of the APIm v3.0 the feault admin can't access to the menu : Dashboards and settings

### Expected Behavior

The default admin who is [ENVIRONMENT] ADMIN - 
[ORGANIZATION] ADMIN can go to the dashboard and settings menu.

### Current Behavior

A popup is displayed with this message : **You do not have sufficient rights to access this resource.**

The default admin is created on the gravitee.yml config like this : 
```
security:
  # When using an authentication providers, use trustAll mode for TLS connections
  # trustAll: false
  providers:  # authentication providers
  - type: memory
    # allow search results to display the user email. Be careful, It may be contrary to the user privacy.
    #      allow-email-in-search-results: true
    # password encoding/hashing algorithm. One of:
    # - bcrypt : passwords are hashed with bcrypt (supports only $2a$ algorithm)
    # - none : passwords are not hashed/encrypted
    # default value is bcrypt
    password-encoding-algo: bcrypt
    users:
    - user:
      username: admin
      firstname: max
      lastname: power
      # Passwords are encoded using BCrypt
      # Password value: go
      password: $2a$10$xx
      roles: ORGANIZATION:ADMIN,ENVIRONMENT:ADMIN
```

Here is the brower logs :
```
vendors~app~vendor-b2afd728075e15277285.js:111 GET https://xxx.fr/management/organizations/DEFAULT/environments/DEFAULT/configuration/dashboards/?reference_type=PLATFORM 403

Transition Rejection($id: 40 type: 6, message: The transition errored, detail: {"data":{"message":"You do not have sufficient rights to access this resource","http_status":403},"status":403,"headers":"function(n){if(t||(t=Ln(e)),n){var i=t[u(n)];return void 0===i&&(i=null),i}return t}","config":{"method":"GET","transformRequest":"function(e){return!H(e)||(t=e,"[object File]"===f.call(t))||function(e){return"[object Blob]"===f.call(e)}(e)||function(e){return"[object FormData]"===f.call(e)}(e)?e:he(e);var t}","transformResponse":"function In(e,t){if(z(e)","paramSerializer":"function(e){if(!e)return"";var t=[];return T(e,(function(e,n){null===e||$(e)||j(e)||(V(e)?y(e,(function(e){t.push(Ce(n)+"="+Ce(wn(e)))})):t.push(Ce(n)+"="+Ce(wn(e))))})),t.join("&")}","jsonpCallbackParam":"callback","url":"https://xxx.fr/management/organizations/DEFAULT/environments/DEFAULT/configuration/dashboards/?reference_type=PLATFORM","headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-Xsrf-Token":"3968425c-8a47-49b2-805c-d462ededee7c"},"cached":false,"timeout":10000,"withCredentials":true},"statusText":"","xhrStatus":"complete"})

vendors~app~vendor-b2afd728075e15277285.js:111 GET https://xxx.fr/management/organizations/DEFAULT/environments/DEFAULT/configuration/dashboards/?reference_type=APPLICATION 403

vendors~app~vendor-b2afd728075e15277285.js:111 GET https://xxx.fr/management/organizations/DEFAULT/environments/DEFAULT/configuration/dashboards/?reference_type=API 403

Transition Rejection($id: 44 type: 2, message: The transition has been superseded by a different transition, detail: Transition#76( 'management.settings'{} -> 'management.apis.list'{"q":"undefined"} ))

Transition Rejection($id: 45 type: 2, message: The transition has been superseded by a different transition, detail: Transition#76( 'management.settings'{} -> 'management.apis.list'{"q":"undefined"} ))
```

### Possible Solution

If I create the first API/plan, I can access to the dashboard and settings page...

### Steps to Reproduce (for bugs)

1. Create a fresh Install
2. Log in with the admin account
3. Try to access the dashboard and settings menu (**without** creating the first api/plan)

### Context

Connect to dashboard page and settings page in a fresh install

### Your Environment

* Version used: v3.0
* Browser Name and version: Chrome
* Operating System and version: Kubernetes
