### ISSUE TITLE
Helm for APIM 3.x fails to download

### ISSUE THREAD

**Issue by frenchyjef** [gravitee-io/issues#3958]
Helm for APIM 3.x fails to download

### Expected Behavior
I should be able to Gravitee APIM 3.x by following instructions at described https://docs.gravitee.io/apim/3.x/apim_installguide_kubernetes.html 

```
helm repo add graviteeio https://helm.gravitee.io
helm install graviteeio-apim3x --namespace edgraph graviteeio/apim3
```

### Current Behavior
Error: failed to download "graviteeio/apim3" (hint: running `helm repo update` may help)

### Context
I am working with Gravitee APIM 3.x in Docker locally but unable to use Helm to deploy to Kubernetes cluster

### Your Environment
Kubernetes

**Comment by brasseld** [comment]
Hi @frenchyjef 

I'm sorry but I'm not able to reproduce the issue, even with a `helm repo update`
Can you confirm it's not a connection issue on your side ?

Regards,

**Comment by frenchyjef** [comment]
Could you share the statements you are executing to get APIM v3 to install through helm3?

I tried installing again and still not working for me. Here are the statements that I am running:

```
C:\test>helm repo add graviteeio https://helm.gravitee.io
"graviteeio" has been added to your repositories

C:\test>helm repo list
NAME                    URL
bitnami                 https://charts.bitnami.com/bitnami
bitnami-azure           https://marketplace.azurecr.io/helm/v1/repo
azure-marketplace       https://marketplace.azurecr.io/helm/v1/repo
elastic                 https://helm.elastic.co
graviteeio              https://helm.gravitee.io

C:\test>helm install graviteeio-apim3x -n test graviteeio/apim3
Error: failed to download "graviteeio/apim3" (hint: running `helm repo update` may help)

C:\test>helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "graviteeio" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "bitnami-azure" chart repository
...Successfully got an update from the "azure-marketplace" chart repository
...Successfully got an update from the "elastic" chart repository
Update Complete. ⎈ Happy Helming!⎈

C:\test>helm install graviteeio-apim3x -n test graviteeio/apim3
Error: failed to download "graviteeio/apim3" (hint: running `helm repo update` may help)
```

When I look deeper into it, yaml file located here [https://helm.gravitee.io/index.yaml](https://helm.gravitee.io/index.yaml) has a section called **apim3** but it points to a tgz file that doesn't exists, i.e. [https://helm.gravitee.io/helm/apim3/apim3-3.0.0.tgz](https://helm.gravitee.io/helm/apim3/apim3-3.0.0.tgz)

```
apim3:
  - apiVersion: v1
    appVersion: 3.0.2
    created: "2020-06-11T15:38:52.735505+02:00"
    description: Official Gravitee.io Helm chart for API Management 3.x
    digest: 6a5aa856b4faf87ea459af52e40c95b7fce335393d082ebeb1f33bbeacdb6fa0
    home: https://gravitee.io
    icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
    name: apim3
    sources:
    - https://github.com/gravitee-io
    urls:
    - https://helm.gravitee.io/helm/apim3/apim3-3.0.0.tgz
    version: 3.0.0
```

The other tgz files (example: [https://helm.gravitee.io/helm/apim/apim-1.29.5.tgz](https://helm.gravitee.io/helm/apim/apim-1.29.5.tgz)) for APIM v1 exist and can be downloaded succesfully
