### ISSUE TITLE
[gateway] CSRFHandler seems not handle proxy context-path

### ISSUE THREAD

**Issue by Adito5393** [gravitee-io/issues#4034]
I am setting the email configuration in 2 containers: **graviteeio/am-management-api** & **graviteeio/am-gateway** (mainly, because I don't know exactly which one is responsible for sending email when a user registers in the AM website within a specific security domain). Following the [GitHub platform v3.x example](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/3.x/docker-compose.yml), I have this relevant code in the docker-compose:
```
am_gateway:
    image: graviteeio/am-gateway:3
    environment:
      # SMTP configuration used to send mails
      - gravitee_email_enabled=true
      - gravitee_email_host=smtp.gmail.com
----------more code---------
am_management:
    image: graviteeio/am-management-api:3
    environment:
      - gravitee_email_enabled=true
      - gravitee_email_host=smtp.gmail.com
```
Following the [technical API guide](https://docs.gravitee.io/am/current/am_installguide_gateway_technical_api.html), within the docker container, I obtain:

1. am_gateway:
`/opt/graviteeio-am-gateway # echo $gravitee_email_enabled`
`true`
`/opt/graviteeio-am-gateway # echo $gravitee_email_host`
`smtp.gmail.com`
`curl http://admin:adminadmin@localhost:18092/_node/configuration`
`"email.enabled" : false,`
`"email.host" : "smtp.my.domain",`
1. am-management-api:
`/opt/graviteeio-am-gateway # echo $gravitee_email_enabled`
`true`
`/opt/graviteeio-am-gateway # echo $gravitee_email_host`
`smtp.gmail.com`
`curl http://admin:adminadmin@localhost:18093/_node/configuration`
`"email.enabled" : false,`
`"email.host" : "smtp.my.domain",`

### Expected Behavior

The curl of the `/_node/configuration` should match with the docker-compose environment settings.

### Current Behavior

The curl of the `/_node/configuration` does not match with the docker-compose environment settings.

### Steps to Reproduce (for bugs)

1. Git clone the platform [v3.x example](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/3.x/)
2. Set the email config via the docker-compose environment value 
3. Check that the value is set within the AM component: am-gateway or am-management-api

### Context

This issue leads to new users unable to register within a specified security domain:
1. Navigate to: `https://am.gravitee.io/auth/SECURITYDOMAIN/register?client_id=**********`
2. Fill in info & click register. Error from the chrome console: `Failed to load resource: the server responded with a status of 403 ()`

### Your Environment

* Version used: AM 3.0.3
* Browser Name and version: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* Operating System and version: Ubuntu 18.04.4 LTS; running Docker version 19.03.11, build 42e35e61f3
