### ISSUE TITLE
AM - ClassNotFoundException JWT nimbus

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#4084]
### Expected Behavior
The AM API should start

### Current Behavior
Does not start, java.lang.ClassNotFoundException: com.nimbusds.jose.JWSAlgorithm

### Possible Solution
review https://github.com/gravitee-io/issues/issues/3581

### Steps to Reproduce (for bugs)
Bumped my instance from 2.10.13 to 2.10.17

### Your Environment
k8s
I've just rollout my deployment with the latest image, like so:
```
kubectl set image deployment/gravitee-am-management-api gravitee-am-management-api=graviteeio/am-management-api:2.10.17 --record=true
kubectl set image deployment/gravitee-am-gateway gravitee-am-gateway=graviteeio/am-gateway:2.10.17 --record=true
kubectl set image deployment/gravitee-am-management-ui gravitee-am-management-ui=graviteeio/am-management-ui:2.10.17 --record=true
```

Maybe there is a jar or some cleaning to do at first?

Full logs: https://gist.github.com/bcollard/b3cc0d5dbea43f017010891902138a5b

**Comment by tcompiegne** [comment]
Hi @bcollard ,

Just try with a fresh installation of the 2.10.17 without issues for now.

Which identity providers are you using to authenticate the admin portal ?

**Comment by bcollard** [comment]
I guess it's the default one, as I didn't customize it (is it mongo or in-memory?)

Here is a piece of config regarding domains and jwt:

```
   domains:
      certificates:
        default:
          keysize: 2048
          alias: default
          keypass: gravitee
          storepass: gravitee
          validity: 365
          algorithm: SHA256withRSA
          name: cn=Gravitee.io

    jwt:
      secret: <custom secret value>
      kid: r3-am-mgmt-api-jwt-secret-kid
      #expire-after: 604800
      #issuer: https://auth.{{ .Values.env_name }}.r3pf.mycompany.com
      #cookie-path: /
      #cookie-domain: .gravitee.io cookie domain (default "")
      #cookie-secure: true
```
