### ISSUE TITLE
[elasticsearch] Connection refused: elasticsearch/172.18.0.2:9200

### ISSUE THREAD

**Issue by sachithmuhandiram** [gravitee-io/issues#4178]
I tried to install `gravitee` using `docker-compose up`, I get following error :

> ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
gio_apim_gateway  | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/172.18.0.2:9200
gio_apim_gateway  | Caused by: java.net.ConnectException: Connection refused

### Expected Behavior

No errors in `docker-compose up` and UI can be loaded and login to it.

### Current Behavior

Getting above mentioned error.

Here `elasticsearch/172.18.0.2:9200`  `172.18.0.2` is container IP address.

### Possible Solution

* Should be a problem with networking.

### Steps to Reproduce (for bugs)

1. `curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o "docker-compose.yml"`
2. Add `ports` to `elasticsearch` 
```
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.7.0}
    container_name: gio_apim_elasticsearch
    restart: always
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    networks:
      - storage
    ports:
      - 9200:9200
      - 9300:9300
```

3. `MGMT_API_URL` and `PORTAL_API_URL`  to have server ip address.

4. `docker-compose pull` and then `docker-compose up`

### Context
* Gravitee API loads API gateway and can create APIs for clients.

### Your Environment

* Version used:                        3.x
* Browser Name and version:  Firefox 68.11.0esr (64-bit)
* Operating System and version:  Ubuntu 18.04 LTS

**Comment by Adito5393** [comment]
Add the user UID in the docker-compose:

```bash
-----
ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    user: "1000:1000"
    networks:
      - storage
```

Check what `uid` you have...probably it is 1000. I think that this will fix your issue! Check [their docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user) for details.

**Comment by sachithmuhandiram** [comment]
> Add the user UID in the docker-compose:
> 
> ```shell
> -----
> ulimits:
>       memlock:
>         soft: -1
>         hard: -1
>       nofile: 65536
>     user: "1000:1000"
>     networks:
>       - storage
> ```
> 
> Check what `uid` you have...probably it is 1000. I think that this will fix your issue! Check [their docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user) for details.

Changed value as you suggested. But still same Error.

**Comment by kumarjitu21** [comment]
Facing the same issue when i try to deploy using helm in kubernetes cluster:

ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
java.net.UnknownHostException: failed to resolve 'graviteeio-apim-elasticsearch-client.default.svc.cluster.local' after 2 queries

Please help me if you have any solutions for this.

**Comment by sachithmuhandiram** [comment]
> Facing the similar issue when i try to deploy using helm in kubernetes cluster:
> 
> ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
> java.net.UnknownHostException: failed to resolve 'graviteeio-apim-elasticsearch-client.default.svc.cluster.local' after 2 queries
> 
> Please help me if you have any solutions for this.

Sorry, cant help. As I still have this issue.

**Comment by BezgertsAI-Sber** [comment]
Hello, 

I have a same issue. I get `docker-compose.yml` file using:
```
curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o "docker-compose.yml"
``` 

After that i pull images using: 
```
docker-compose pull
```
And after that i run `gravitee` using:
```
docker-compose up
```
I get following errors:
```
gio_apim_gateway  | 12:40:51.518 [vert.x-eventloop-thread-1] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
gio_apim_gateway  | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/172.18.0.3:9200
gio_apim_gateway  | Caused by: java.net.ConnectException: Connection refused
gio_apim_gateway  | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
gio_apim_gateway  | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
gio_apim_gateway  | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
gio_apim_gateway  | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
gio_apim_gateway  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
gio_apim_gateway  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
gio_apim_gateway  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
gio_apim_gateway  | 	at java.base/java.lang.Thread.run(Unknown Source)
gio_apim_gateway  | 12:40:51.537 [vert.x-eventloop-thread-1] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
gio_apim_gateway  | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/172.18.0.3:9200
gio_apim_gateway  | Caused by: java.net.ConnectException: Connection refused
gio_apim_gateway  | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
gio_apim_gateway  | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
gio_apim_gateway  | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
gio_apim_gateway  | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
gio_apim_gateway  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
gio_apim_gateway  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
gio_apim_gateway  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
gio_apim_gateway  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
gio_apim_gateway  | 	at java.base/java.lang.Thread.run(Unknown Source)

gio_apim_management_api | 12:40:53.464 [vert.x-eventloop-thread-5] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
gio_apim_management_api | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/172.18.0.3:9200
gio_apim_management_api | Caused by: java.net.ConnectException: Connection refused
gio_apim_management_api | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
gio_apim_management_api | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
gio_apim_management_api | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
gio_apim_management_api | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
gio_apim_management_api | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
gio_apim_management_api | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
gio_apim_management_api | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
gio_apim_management_api | 	at java.base/java.lang.Thread.run(Unknown Source)
gio_apim_management_api | 12:40:53.480 [vert.x-eventloop-thread-6] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
gio_apim_management_api | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/172.18.0.3:9200
gio_apim_management_api | Caused by: java.net.ConnectException: Connection refused
gio_apim_management_api | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
gio_apim_management_api | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
gio_apim_management_api | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
gio_apim_management_api | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
gio_apim_management_api | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
gio_apim_management_api | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
gio_apim_management_api | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
gio_apim_management_api | 	at java.base/java.lang.Thread.run(Unknown Source)

```
Can anybody help with this errors? How to fix it?

**Comment by Adito5393** [comment]
I don't have the time to help you but if I would be you I would compare the docker-compose you use & gives you that error with the one from the [platform folder](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/3.x/docker-compose.yml)

I can confirm that the platform's docker-compose works without problems.

**Comment by brasseld** [comment]
What's the status of the elasticsearch container ? Can you check the logs please ?

**Comment by BezgertsAI-Sber** [comment]
> What's the status of the elasticsearch container ? Can you check the logs please ?

Status of container is `UP`

**Comment by BezgertsAI-Sber** [comment]
> I don't have the time to help you but if I would be you I would compare the docker-compose you use & gives you that error with the one from the [platform folder](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/3.x/docker-compose.yml)
> 
> I can confirm that the platform's docker-compose works without problems.

Thank you for advice. I try with `docker-compose.yml` from  the [platform folder](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/3.x/docker-compose.yml), but i get the same error:

```
gio_apim_management_api | 10:41:27.945 [vert.x-eventloop-thread-3] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
gio_apim_management_api | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/172.18.0.3:9200
gio_apim_management_api | Caused by: java.net.ConnectException: Connection refused
gio_apim_management_api | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
gio_apim_management_api | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
gio_apim_management_api | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
gio_apim_management_api | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
gio_apim_management_api | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
gio_apim_management_api | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
gio_apim_management_api | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
gio_apim_management_api | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
gio_apim_management_api | 	at java.base/java.lang.Thread.run(Unknown Source)
```

And besides I got a lot of errors when connecting to MongoDB:

```
apim_gateway_1     | org.springframework.dao.DataAccessResourceFailureException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongodb:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongodb}, caused by {java.net.UnknownHostException: mongodb}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongodb:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongodb}, caused by {java.net.UnknownHostException: mongodb}}]
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:90)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2774)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:540)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate.insertDocument(MongoTemplate.java:1429)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate.doInsert(MongoTemplate.java:1237)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:1171)
apim_gateway_1     | 	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.insert(SimpleMongoRepository.java:244)
apim_gateway_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apim_gateway_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
apim_gateway_1     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
apim_gateway_1     | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
apim_gateway_1     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
apim_gateway_1     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
apim_gateway_1     | 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
apim_gateway_1     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
apim_gateway_1     | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
apim_gateway_1     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
apim_gateway_1     | 	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
apim_gateway_1     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
apim_gateway_1     | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
apim_gateway_1     | 	at com.sun.proxy.$Proxy87.insert(Unknown Source)
apim_gateway_1     | 	at io.gravitee.repository.mongodb.management.MongoEventRepository.create(MongoEventRepository.java:67)
apim_gateway_1     | 	at io.gravitee.repository.mongodb.management.MongoEventRepository.create(MongoEventRepository.java:40)
apim_gateway_1     | 	at io.gravitee.gateway.services.hearbeat.HeartbeatService.doStart(HeartbeatService.java:96)
apim_gateway_1     | 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
apim_gateway_1     | 	at io.gravitee.node.plugins.service.impl.ServiceManagerImpl.doStart(ServiceManagerImpl.java:47)
apim_gateway_1     | 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
apim_gateway_1     | 	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
apim_gateway_1     | 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
apim_gateway_1     | 	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
apim_gateway_1     | 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
apim_gateway_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apim_gateway_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
apim_gateway_1     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
apim_gateway_1     | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
apim_gateway_1     | 	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
apim_gateway_1     | 	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
apim_gateway_1     | Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongodb:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongodb}, caused by {java.net.UnknownHostException: mongodb}}]
apim_gateway_1     | 	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
apim_gateway_1     | 	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:152)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:103)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:284)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:208)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1053)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:503)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:487)
apim_gateway_1     | 	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:481)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate$6.doInCollection(MongoTemplate.java:1436)
apim_gateway_1     | 	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:538)
apim_gateway_1     | 	... 40 common frames omitted

```

**Comment by aelamrani** [comment]
@BezgertsAI-Sber Can you check the status of the ES and Mongodb containers?

**Comment by jasseral** [comment]
> Facing the similar issue when i try to deploy using helm in kubernetes cluster:
> 
> ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch java.net.UnknownHostException: failed to resolve 'graviteeio-apim-elasticsearch-client.default.svc.cluster.local' after 2 queries
> 
> Please help me if you have any solutions for this.

Hey de same here , do you found the solution ?

**Comment by Farb** [comment]
@jasseral @brasseld @aelamrani @kumarjitu21 @sachithmuhandiram 

I met the same problem. The problem is solved after I changed the version . 

This docker compose file with higher version is ok.
``` yml
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    image: elasticsearch:7.9.0
    container_name: elasticsearch
    # --restart=always ： 开机启动，失败也会一直重启；
    # --restart=on-failure:10 ： 表示最多重启10次
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node
      # 锁定物理内存地址，防止elasticsearch内存被交换出去,也就是避免es使用swap交换分区，频繁的交换，会导致IOPS变高；
      - bootstrap.memory_lock=true
      # 设置时区
      - TZ=Asia/Shanghai
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  oap:
    image: apache/skywalking-oap-server:8.9.1
    container_name: oap
    restart: always
    # 设置依赖的容器
    depends_on:
      elasticsearch:
        condition: service_healthy
    # 关联ES的容器，通过容器名字来找到相应容器，解决IP变动问题
    links:
      - elasticsearch
    # 端口映射
    ports:
      - "11800:11800"
      - "12800:12800"
    # 监控检查
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      # 每间隔30秒执行一次
      interval: 30s
      # 健康检查命令运行超时时间，如果超过这个时间，本次健康检查就被视为失败；
      timeout: 10s
      # 当连续失败指定次数后，则将容器状态视为 unhealthy，默认 3 次。
      retries: 3
      # 应用的启动的初始化时间，在启动过程中的健康检查失效不会计入，默认 0 秒。
      start_period: 10s
    environment:
      # 指定存储方式
      SW_STORAGE: elasticsearch
      # 指定存储的地址
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      TZ: Asia/Shanghai
      # JAVA_OPTS: "-Xms2048m -Xmx2048m"

  ui:
    image: apache/skywalking-ui:8.9.1
    container_name: skywalking-ui
    restart: always
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8088:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      TZ: Asia/Shanghai

```

This docker compose file with higher version did not work.

```yml
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    # --restart=always ： 开机启动，失败也会一直重启；
    # --restart=on-failure:10 ： 表示最多重启10次
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node
      # 锁定物理内存地址，防止elasticsearch内存被交换出去,也就是避免es使用swap交换分区，频繁的交换，会导致IOPS变高；
      - bootstrap.memory_lock=true
      # 设置时区
      - TZ=Asia/Shanghai
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  oap:
    image: apache/skywalking-oap-server:10.1.0
    container_name: oap
    restart: always
    # 设置依赖的容器
    depends_on:
      elasticsearch:
        condition: service_healthy
    # 关联ES的容器，通过容器名字来找到相应容器，解决IP变动问题
    links:
      - elasticsearch
    # 端口映射
    ports:
      - "11800:11800"
      - "12800:12800"
    # 监控检查
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      # 每间隔30秒执行一次
      interval: 30s
      # 健康检查命令运行超时时间，如果超过这个时间，本次健康检查就被视为失败；
      timeout: 10s
      # 当连续失败指定次数后，则将容器状态视为 unhealthy，默认 3 次。
      retries: 3
      # 应用的启动的初始化时间，在启动过程中的健康检查失效不会计入，默认 0 秒。
      start_period: 10s
    environment:
      # 指定存储方式
      SW_STORAGE: elasticsearch
      # 指定存储的地址
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      TZ: Asia/Shanghai
      # JAVA_OPTS: "-Xms2048m -Xmx2048m"

  ui:
    image: apache/skywalking-ui:10.1.0
    container_name: skywalking-ui
    restart: always
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8088:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      TZ: Asia/Shanghai

```
