### ISSUE TITLE
[APIM] Gateway return "No context-path matches the request URI." with a correct context-path

### ISSUE THREAD

**Issue by michaelZer** [gravitee-io/issues#4187]
Hello !
I use Gravitee with Kubernetes and I created an API on the UI-Management-API named "Test API" (entrypoint="/test", endpoint="http://api.gravitee.io/echo") with a Keyless Plan (no policies or request limitations).
Test API export file :
```json
{
  "name": "Test API",
  "version": "1.0",
  "description": "Test",
  "visibility": "PUBLIC",
  "paths": {
    "/": []
  },
  "resources": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "roles": [
        "0d619322-b4ff-49e0-a193-22b4ff29e0d2"
      ]
    }
  ],
  "pages": [
    {
      "id": "dfc51a7d-c4fc-4aad-851a-7dc4fc0aad18",
      "name": "Aside",
      "type": "SYSTEM_FOLDER",
      "order": 0,
      "published": true,
      "lastModificationDate": 1597327046610,
      "contentType": "application/json",
      "homepage": false,
      "api": "ea6d12bd-0364-49f2-ad12-bd036409f200"
    }
  ],
  "plans": [
    {
      "id": "ee01a6fa-ac64-4c53-81a6-faac640c530d",
      "name": "Test Plan",
      "description": "Test Plan",
      "validation": "AUTO",
      "security": "KEY_LESS",
      "type": "API",
      "status": "PUBLISHED",
      "api": "ea6d12bd-0364-49f2-ad12-bd036409f200",
      "order": 0,
      "characteristics": [],
      "created_at": 1597327047211,
      "updated_at": 1597327047211,
      "paths": {
        "/": []
      },
      "comment_required": false
    }
  ],
  "metadata": [
    {
      "key": "email-support",
      "name": "email-support",
      "format": "MAIL",
      "value": "${(api.primaryOwner.email)!''}",
      "defaultValue": "support@change.me",
      "apiId": "ea6d12bd-0364-49f2-ad12-bd036409f200"
    }
  ],
  "path_mappings": [],
  "proxy": {
    "virtual_hosts": [
      {
        "path": "/test"
      }
    ],
    "strip_context_path": false,
    "preserve_host": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "http://api.gravitee.io/echo",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "inherit": true
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  },
  "response_templates": {}
}
```

I published this API and can see it through the link with "/management/organizations/DEFAULT/environments/DEFAULT/apis".
<img width="865" alt="API Management" src="https://user-images.githubusercontent.com/56668970/90249714-3e6d2b00-de3b-11ea-8ade-862204035b3b.png">
However, when I use the Gateway, it returns me a "No context-path matches the request URI." error...
<img width="832" alt="API Gateway" src="https://user-images.githubusercontent.com/56668970/90249683-32816900-de3b-11ea-94b1-05d4dc5bf307.png">

### Expected Behavior
The link with "/gateway/test" should return the same result than "http://api.gravitee.io/echo".

### Current Behavior
The link with "/gateway/test"  return "No context-path matches the request URI.".

### Possible Solution
I saw a solution that suggested the Gateway and Management-API aren't linked to the same MongoDB instance, but I have only one instance of MongoDB.

### Steps to Reproduce (for bugs)
My values.yaml file for deploying on kubernetes :
```yaml
mongodb-replicaset:
  enabled: true
  replicas: 3
  replicaSetName: rs0
  auth:
    enabled: false
    adminUser: username
    adminPassword: password
    metricsUser: metrics
    metricsPassword: password
    key: keycontent
    # existingKeySecret:
    # existingAdminSecret:
    # existingMetricsSecret:
  image:
    repository: mongo
    tag: 3.6
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistentVolume:
    enabled: true
    storageClass: sata
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  configmap: {}

elasticsearch:
  enabled: true
  cluster:
    name: "elasticsearch"
    env:
      MINIMUM_MASTER_NODES: "2"
    plugins: []

  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
    tag: "6.7.0"
  client:
    name: client
    replicas: 2
    heapSize: "512m"
    # additionalJavaOpts: "-XX:MaxRAM=512m"
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "25m"
        memory: "512Mi"
  master:
    name: master
    replicas: 3
    heapSize: "512m"
    # additionalJavaOpts: "-XX:MaxRAM=512m"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "4Gi"
      storageClass: sata
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "25m"
        memory: "512Mi"

  data:
    name: data
    exposeHttp: false
    replicas: 2
    heapSize: "512m"
    # additionalJavaOpts: "-XX:MaxRAM=512m"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "30Gi"
      storageClass: sata
    resources:
      limits:
        cpu: "1"
        memory: "2048Mi"
      requests:
        cpu: "25m"
        memory: "1536Mi"
```

**Comment by tboksebeld** [comment]
Hi michael, where did you defined the _/gateway_ or your _**/gateway**/test_ relative url ? 
Locally on your gateway server, if you ask for 
`HTTP GET http://localhost:[gateway_port----default_is_8082]/test`
 what is the response ?

**Comment by michaelZer** [comment]
Hi and thank you for your rapid answer.
By default, I have :
 - /gateway : to reach my gateway
 - /management : to reach the api management
 - /console : to reach my UI
 - / : to reach the portal
So my Test API just need a "/test" from the gateway. It's why I suppose that I need to use "/gateway/test" (I'm not sure I'm answering your question).
By the way, I'm not on localhost but a distant server.

This is my result if I'm doing the GET in my gateway pod :
<img width="504" alt="Screenshot wget" src="https://user-images.githubusercontent.com/56668970/90260742-3964a780-de4c-11ea-8ee5-f8537f498286.png">

**Comment by tboksebeld** [comment]
I have been in your situation few days/hours ago, so i assume i can help you a bit :)
when you are inside your pod, try the localhost url.
You should really try `wget http://localhost:8082/test`
By default, gateway is locally exposed on port `8082`, and doesn't have `/gateway` base uri.

**Comment by michaelZer** [comment]
There is my wget :
<img width="941" alt="Screenshot" src="https://user-images.githubusercontent.com/56668970/90266096-cceda680-de53-11ea-9978-a059257cb6bc.png">
You're right I can access the gateway from my pod with localhost ! Thanks :)

But how can I access the gateway from my browser ? I try the same on my browser but it doesn't accept it..
<img width="474" alt="Screenshot2" src="https://user-images.githubusercontent.com/56668970/90266635-949a9800-de54-11ea-8b4a-09d8a18b98d3.png">


And why do I have to access it with localhost when I use a different hostname to access my Api-Management, UI and Portal ?
I had follow this tutorial : https://medium.com/graviteeio/gravitee-io-apim-on-kubernetes-c0c0107d5e3c
Maybe this will show you how I see the use of Gateway, and the difficulty I have to understand why we use localhost.

**Comment by tboksebeld** [comment]
The local success only show that the gateway is working fine, and your api is correctly configured.
Now, you have to "troubleshoot" its exposition.

In the tutorial, the gateway is apparently exposed by `Ingress` behind `/gateway` uri.
First, you could check what is the url called when you use your public uri : 

1. Call `http(s)://_your_public_hosts_/gateway/test`
2. Check gateway's log : idk if you can do it through kubernetes (never used), but locally, you can check `opt/graviteeio-gateway/gravitee.log`
3. The last row will show you the real url received by the gateway. something like `16:06:37.667 [vert.x-eventloop-thread-4] [] WARN  i.g.g.r.p.notfound.NotFoundProcessor - No handler can be found for request /test-for-michaelZer, returning NOT_FOUND (404)`
4. If Ingress does not perform any rewrite url, gateway should receive `/gateway/test` when it is only supporting `/test` for now
5. If that's the case, then you just have to fix that. 
6. First solution : change your API config via `management-ui` and expose it behind `/gateway/test`
7. Or : perform a rewrite url on Ingress to transform `http://public_host/gateway/test` into `http://private_host/test`

**Comment by michaelZer** [comment]
Thank you for your answer.
Actually, I have a new problem with my Gravitee installation.. It seems that my pods are no longer working.
<img width="463" alt="Kubectl get pod" src="https://user-images.githubusercontent.com/56668970/90402382-a6bc4680-e09f-11ea-9696-cf684fc48efd.png">

And I can't access my Gravitee components (like UI) by my browser.
<img width="361" alt="Browser Gravitee error" src="https://user-images.githubusercontent.com/56668970/90402512-d9663f00-e09f-11ea-85a0-44cf698dd9ff.png">

I didn't changed my values.yaml configuration file. I tried to delete my PVCs (Persistent Volume Claim) and reinstall the helm, but I have the same result..

In order to answer your previous question, I can see my logs with Kubernetes :
Gateway (I stopped it because it was infinite) :
[gravitee_gateway.log](https://github.com/gravitee-io/issues/files/5084633/gravitee_gateway.log)
Api :
[gravitee_api.log](https://github.com/gravitee-io/issues/files/5084636/gravitee_api.log)

**Comment by michaelZer** [comment]
Ok my new issue is resolved. 
There is the good values.yaml file :
```yaml
adminEmail: null
adminFirstName: null
adminLastName: null
adminPasswordBcrypt: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
alerts:
  enabled: false
  endpoints:
  - http://localhost:8072/
  security:
    enabled: false
    password: adminadmin
    username: admin
api:
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  enabled: true
  http:
    api:
      entrypoint: /
    client:
      proxy:
        http:
          host: localhost
          password: null
          port: 3128
          username: null
        https:
          host: localhost
          password: null
          port: 3128
          username: null
        type: HTTP
      timeout: 10000
    services:
      core:
        http:
          authentication:
            password: adminadmin
          host: localhost
          port: 18083
        ingress:
          enabled: false
        service:
          enabled: false
  image:
    pullPolicy: Always
    repository: graviteeio/apim-management-api
  ingress:
    management:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          etag on;
          proxy_pass_header ETag;
          proxy_set_header if-match "";
      enabled: true
      hosts:
      - gravitee-dev.esa-maap.org
      path: /management
      tls:
      - hosts:
        - gravitee-dev.esa-maap.org
        secretName: esa-maap-ssl-key
    portal:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          etag on;
          proxy_pass_header ETag;
          proxy_set_header if-match "";
      enabled: true
      hosts:
      - gravitee-dev.esa-maap.org
      path: /portal
      tls:
      - hosts:
        - gravitee-dev.esa-maap.org
        secretName: esa-maap-ssl-key
  logging:
    debug: false
    file:
      enabled: true
      encoderPattern: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%n'
      rollingPolicy: |
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${gravitee.management.log.dir}/gravitee_%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
        </rollingPolicy>
    graviteeLevel: DEBUG
    jettyLevel: INFO
    stdout:
      encoderPattern: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  name: api
  ratingEnabled: true
  reloadOnConfigChange: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  restartPolicy: OnFailure
  service:
    externalPort: 83
    internalPort: 8083
    type: ClusterIP
  ssl:
    enabled: false
  supportEnabled: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  user:
    anynomizeOnDelete: false
    login:
      defaultApplication: true
chaos:
  enabled: false
elasticsearch:
  appVersion: 6.8.2
  chownInitContainer:
    enabled: true
  client:
    antiAffinity: soft
    heapSize: 512m
    hooks: {}
    ingress:
      annotations: {}
      enabled: false
      hosts:
      - chart-example.local
      path: /
      tls: []
    initResources: {}
    loadBalancerIP: {}
    loadBalancerSourceRanges: {}
    name: client
    nodeAffinity: {}
    nodeSelector: {}
    podDisruptionBudget:
      enabled: false
      minAvailable: 1
    priorityClassName: ""
    replicas: 2
    resources:
      limits:
        cpu: "1"
        memory: 1024Mi
      requests:
        cpu: 25m
        memory: 512Mi
    serviceType: ClusterIP
    tolerations: []
  cluster:
    additionalJavaOpts: ""
    bootstrapShellCommand: ""
    config: {}
    env:
      MINIMUM_MASTER_NODES: "2"
    log4j2Properties: |
      status = error
      appender.console.type = Console
      appender.console.name = console
      appender.console.layout.type = PatternLayout
      appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n
      rootLogger.level = info
      rootLogger.appenderRef.console.ref = console
      logger.searchguard.name = com.floragunn
      logger.searchguard.level = info
    loggingYml:
      appender:
        console:
          layout:
            conversionPattern: '[%d{ISO8601}][%-5p][%-25c] %m%n'
            type: consolePattern
          type: console
      es.logger.level: INFO
      logger:
        action: DEBUG
        com.amazonaws: WARN
      rootLogger: ${es.logger.level}, console
    name: elasticsearch
    plugins: []
    xpackEnable: false
  data:
    antiAffinity: soft
    exposeHttp: false
    heapSize: 512m
    hooks:
      drain:
        enabled: true
    initResources: {}
    name: data
    nodeAffinity: {}
    nodeSelector: {}
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      name: data
      size: 30Gi
      storageClass: sata
    podDisruptionBudget:
      enabled: false
      maxUnavailable: 1
    podManagementPolicy: OrderedReady
    priorityClassName: ""
    readinessProbe:
      httpGet:
        path: /_cluster/health?local=true
        port: 9200
      initialDelaySeconds: 5
    replicas: 2
    resources:
      limits:
        cpu: "1"
        memory: 2048Mi
      requests:
        cpu: 25m
        memory: 1536Mi
    terminationGracePeriodSeconds: 3600
    tolerations: []
    updateStrategy:
      type: OnDelete
  enabled: true
  extraInitContainers: ""
  forceIpv6: false
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: docker.elastic.co/elasticsearch/elasticsearch-oss
    tag: 6.7.0
  initImage:
    pullPolicy: Always
    repository: busybox
    tag: latest
  master:
    antiAffinity: soft
    exposeHttp: false
    heapSize: 512m
    hooks: {}
    initResources: {}
    name: master
    nodeAffinity: {}
    nodeSelector: {}
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      name: data
      size: 4Gi
      storageClass: sata
    podDisruptionBudget:
      enabled: false
      minAvailable: 2
    podManagementPolicy: OrderedReady
    priorityClassName: ""
    readinessProbe:
      httpGet:
        path: /_cluster/health?local=true
        port: 9200
      initialDelaySeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: 1024Mi
      requests:
        cpu: 25m
        memory: 512Mi
    tolerations: []
    updateStrategy:
      type: OnDelete
  podSecurityPolicy:
    annotations: {}
    enabled: false
  securityContext:
    enabled: false
    runAsUser: 1000
  serviceAccounts:
    client:
      create: true
    data:
      create: true
    master:
      create: true
  sysctlInitContainer:
    enabled: true
  testFramework:
    image: dduportal/bats
    tag: 0.4.0
es:
  cluster: elasticsearch
  enabled: true
  endpoints:
  - http://graviteeio-apim3x-elasticsearch-client.default.svc.cluster.local:9200
  index: gravitee
  security:
    enabled: false
    password: example
    username: example
  ssl:
    enabled: false
extraInMemoryUsers: |
  - user:
    username: user
    # Password value: password
    password: $2a$10$9kjw/SH9gucCId3Lnt6EmuFreUAcXSZgpvAYuW2ISv7hSOhHRH1AO
    roles: ORGANIZATION:USER, ENVIRONMENT:USER
    # Useful to receive notifications
    #email:
    #firstName:
    #lastName:
  - user:
    username: api1
    # Password value: api1
    password: $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji
    # You can declare multiple roles using comma separator
    roles: ORGANIZATION:USER, ENVIRONMENT:API_PUBLISHER
    #email:
    #firstName:
    #lastName:
  - user:
    username: application1
    # Password value: application1
    password: $2a$10$2gtKPYRB9zaVaPcn5RBx/.3T.7SeZoDGs9GKqbo9G64fKyXFR1He.
    roles: ORGANIZATION:USER, ENVIRONMENT:USER
    #email:
    #firstName:
    #lastName:
gateway:
  apiKey:
    header: X-Gravitee-Api-Key
    param: api-key
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  enabled: true
  image:
    pullPolicy: Always
    repository: graviteeio/apim-gateway
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    enabled: true
    hosts:
    - gravitee-dev.esa-maap.org
    path: /gateway
    tls:
    - hosts:
      - gravitee-dev.esa-maap.org
      secretName: esa-maap-ssl-key
  logging:
    debug: false
    file:
      enabled: true
      encoderPattern: '%d{HH:mm:ss.SSS} [%thread] [%X{api}] %-5level %logger{36} -
        %msg%n'
      rollingPolicy: |
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${gravitee.home}/logs/gravitee_%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
        </rollingPolicy>
    graviteeLevel: DEBUG
    jettyLevel: WARN
    stdout:
      encoderPattern: '%d{HH:mm:ss.SSS} [%thread] [%X{api}] %-5level %logger{36} -
        %msg%n'
  name: gateway
  reloadOnConfigChange: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    externalPort: 82
    internalPort: 8082
    type: ClusterIP
  ssl:
    clientAuth: false
    enabled: false
  type: Deployment
  websocket: false
inMemoryAuth:
  allowEmailInSearchResults: false
  enabled: true
jwtSecret: myJWT4Gr4v1t33_S3cr3t
ldap:
  authentication:
    group:
      base: ou=gravitee,ou=groups
      filter: member={0}
      role:
        admin: LDAP_GROUP_ADMIN
        attribute: sAMAccountName
        consumer: LDAP_GROUP_CONSUMER
        publisher: LDAP_GROUP_PUBLISHER
        user: LDAP_GROUP_USER
    user:
      base: ou=users
      filter: sAMAccountName={0}
      photo: thumbnailPhoto
  context:
    base: dc=example,dc=com
    password: pass@12345
    url: ldap://ldap.example.com
    user: user@example.com
  enabled: false
  lookup:
    allowEmailInSearchResults: false
    user:
      base: ou=users
      filter: (&(objectClass=person)(|(cn=*{0}*)(sAMAccountName={0})))
mongo:
  auth:
    enabled: false
    password: null
    source: admin
    username: null
  connectTimeoutMS: 30000
  dbhost: graviteeio-apim3x-mongodb-replicaset
  dbname: gravitee
  dbport: 27017
  rs: rs0
  rsEnabled: true
  socketKeepAlive: false
  sslEnabled: false
mongodb-replicaset:
  affinity: {}
  auth:
    adminPassword: password
    adminUser: username
    enabled: false
    existingAdminSecret: ""
    existingKeySecret: ""
    existingMetricsSecret: ""
    key: keycontent
    metricsPassword: password
    metricsUser: metrics
  configmap: {}
  copyConfigImage:
    pullPolicy: IfNotPresent
    repository: busybox
    tag: 1.29.3
  enabled: true
  extraLabels: {}
  extraVars: {}
  fullnameOverride: ""
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: mongo
    tag: 3.6
  imagePullSecrets: []
  init:
    resources: {}
    timeout: 900
  initMongodStandalone: ""
  installImage:
    pullPolicy: IfNotPresent
    repository: unguiculus/mongodb-install
    tag: 0.7
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  metrics:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      repository: bitnami/mongodb-exporter
      tag: 0.10.0-debian-9-r71
    path: /metrics
    port: 9216
    prometheusServiceDiscovery: true
    resources: {}
    securityContext:
      enabled: true
      runAsUser: 1001
    socketTimeout: 3s
    syncTimeout: 1m
  nameOverride: ""
  nodeSelector: {}
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    annotations: {}
    enabled: true
    size: 1Gi
    storageClass: sata
  podAnnotations: {}
  podDisruptionBudget: {}
  port: 27017
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaSetName: rs0
  replicas: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  securityContext:
    enabled: true
    fsGroup: 999
    runAsNonRoot: true
    runAsUser: 999
  serviceAnnotations: {}
  skipInitialization: false
  terminationGracePeriodSeconds: 30
  tls:
    enabled: false
    mode: requireSSL
  tolerations: []
portal:
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  enabled: true
  image:
    pullPolicy: Always
    repository: graviteeio/apim-portal-ui
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        etag on;
        proxy_pass_header ETag;
    enabled: true
    hosts:
    - gravitee-dev.esa-maap.org
    path: /
    tls:
    - hosts:
      - gravitee-dev.esa-maap.org
      secretName: esa-maap-ssl-key
  name: portal
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  service:
    externalPort: 8003
    internalPort: 8080
    name: nginx
    type: ClusterIP
smtp:
  enabled: false
  from: info@example.com
  host: smtp.example.com
  password: example.com
  port: 25
  properties:
    auth: true
    starttlsEnable: false
  subject: '[gravitee] %s'
  username: info@example.com
ui:
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  documentationLink: http://docs.gravitee.io/
  enabled: true
  image:
    pullPolicy: Always
    repository: graviteeio/apim-management-ui
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        etag on;
        proxy_pass_header ETag;
      nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    enabled: true
    hosts:
    - gravitee-dev.esa-maap.org
    path: /console(/|$)(.*)
    tls:
    - hosts:
      - gravitee-dev.esa-maap.org
      secretName: esa-maap-ssl-key
  managementTitle: API Management
  name: ui
  portal:
    analytics:
      enabled: false
      trackingId: ""
    apikeyHeader: X-Gravitee-Api-Key
    rating:
      enabled: false
    support:
      enabled: true
    userCreation:
      enabled: false
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  scheduler:
    tasks: 10
  service:
    externalPort: 8002
    internalPort: 8080
    name: nginx
    type: ClusterIP
  theme:
    loader: assets/gravitee_logo_anim.gif
    logo: themes/assets/GRAVITEE_LOGO1-01.png
    name: default
  title: Management UI
``` 

I'm gonna try your steps and I will tell you the result
