### ISSUE TITLE
[kubernetes] Helm chart issues, super easy to reproduce

### ISSUE THREAD

**Issue by DarkBlaez** [gravitee-io/issues#4262]
The current helm chart for apim3-3.0.10.tgz fails immediately. This error would have been immediate. To clarify, this takes place in the updated helm repo, this also happens with the version pulled from git.

Error: template: apim3/templates/api/api-deployment.yaml:29:28: executing "apim3/templates/api/api-deployment.yaml" at <include (print $.Template.BasePath "/api/api-configmap.yaml") .>: error calling include: template: apim3/templates/api/api-configmap.yaml:229:36: executing "apim3/templates/api/api-configmap.yaml" at <.Values.notifiers.smtp.starttls.enabled>: nil pointer evaluating interface {}.enabled

Please advise? It appears the file change check is blowing errors. While this should work, not sure why it would error out upon a fresh install. As in, it's not even executing the chart, just straight to an error.

Also, a bit of advice, unification on terms would be nice.... i.e starttlsEnable vs starttls.enabled as your attributes. Which should you settle on, almost as if two different individuals worked on the same section of the values/configmap. Settle on one or the other

```yaml
  enabled: true
  host: smtp.example.com
  port: 25
  from: info@example.com
  username: info@example.com
  password: example.com
  subject: "[gravitee] %s"
  properties:
    auth: true
    starttlsEnable: false
    #localhost: apim.example.com

notifiers:
  smtp:
    enabled: true
    host: ${email.host}
    subject: ${email.subject}
    port: ${email.port}
    from: ${email.from}
    username: ${email.username}
    password: ${email.password}
    starttls.enabled: false
    #    ssl:
    #      trustAll: false
    #      keyStore:
    #      keyStorePassword:
```

Thanks
DB
