### ISSUE TITLE
[policy] [groovy] Groovy scripting is not found basic method

### ISSUE THREAD

**Issue by Emmanuel35** [gravitee-io/issues#4339]
### Expected Behavior

We are using groovy script with md5() method.
Script used is:
```
def ts = new Date()
ts = ts.getTime().toString()
request.parameters.'ts' = ts
 
def pubKey = 'aaaa'
def privKey = 'bbbb'
 
def hash = (ts + privKey + pubKey).md5()

```
Result should be a md5 value.

### Current Behavior

We have an 500 error generated by Gravitee:
```
{
    "message": "Failed to resolve method [ class java.lang.String md5  ]",
    "http_status_code": 500
}
```

#### Complete log
```
ava.lang.SecurityException: Failed to resolve method [ class java.lang.String md5  ]
	at io.gravitee.policy.groovy.sandbox.SecuredInterceptor.onMethodCall(SecuredInterceptor.java:48)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
	at 844464e39626e8ec8b70f3e9f5ab6d647288345e.run(844464e39626e8ec8b70f3e9f5ab6d647288345e:8)
	at io.gravitee.policy.groovy.sandbox.SecuredGroovyShell.evaluate(SecuredGroovyShell.java:99)
	at io.gravitee.policy.groovy.GroovyPolicy.executeScript(GroovyPolicy.java:162)
	at io.gravitee.policy.groovy.GroovyPolicy.onRequest(GroovyPolicy.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:95)

```
 
### Possible Solution

Not found.

### Steps to Reproduce (for bugs)

1. Add a new "Groovy" policy on an operation of an API.
2. Copy script into "On request script"
3. Deploy API and call HTTP method

### Your Environment

* Version used: 3.1.2
* Browser Name and version: Chrome
* Operating System and version: CentOS 7

**Comment by brasseld** [comment]
Hi @Emmanuel35 

`Failed to resolve method [ class java.lang.String md5  ]`

I think you have an issue with your script. This method doesn't not exist.

Regards,

**Comment by jhaeyaert** [comment]
Hi, seems related to the groovy sandbox feature. You are using a method that is not in the whitelist (probably this one should be whitelist be default).

After digging a little, the method you use seems to be `org.codehaus.groovy.runtime.EncodingGroovyMethods md5 java.lang.CharSequence`

As a workaround, I suggest you to add it on the gravitee.yml (`groovy.whitelist.list`). Also, make sure to add it on both gateway and management sides.

```yaml
#groovy:
  # Allows to define which methods, fields, constructors, annotations or classes are accessible to the Groovy Script (/!\ caution, changing default whitelist may expose you to security issues).
  # A complete list of default whitelist methods can be found here (https://raw.githubusercontent.com/gravitee-io/gravitee-policy-groovy/master/src/main/resources/groovy-whitelist).
#  whitelist:
    # Allows to define if the specified list of methods, fields, constructors or classes should be append to the default one or should replace it.
    # We recommend you to always choose 'append' unless you absolutely know what you are doing.
#    mode: append
    # Define the list of classes, methods, constructors, fields or annotations to append (or set) to made accessible to the Groovy Script.
    # start with 'method' to allow a specific method (complete signature).
    # start with 'class' to allow a complete class. All methods, constructors and fields of the class will then be accessible.
    # start with 'new' to allow a specific constructor (complete signature).
    # start with 'field' to allow access to a specific field of a class.
    # start with 'annotation' to allow use of a specific annotation.
#    list:
      # Ex: allow access to DateTimeFormatter.ofLocalizedDate(FormatStyle) method
      # - method java.time.format.DateTimeFormatter ofLocalizedDate java.time.format.FormatStyle
      # Ex: allow access to all methods, constructors and fields of DateTimeFormatter class
      # - class java.time.format.DateTimeFormatter
      # Ex: allow usage of field Integer.MAX_VALUE
      # - field java.lang.Integer MAX_VALUE
      # Ex: allow usage of @Override annotation
      # - annotation java.lang.Override
```

And if you want to contribute, you can open a PR to add this convenient method to the default whitelist ;-)

**Comment by Emmanuel35** [comment]
I had in gravitee.yaml
```
groovy:
  # Allows to define which methods, fields, constructors, annotations or classes are accessible to the Groovy Script (/!\ caution, changing default whitelist may expose you to security issues).
  # A complete list of default whitelist methods can be found here (https://raw.githubusercontent.com/gravitee-io/gravitee-policy-groovy/master/src/main/resources/groovy-whitelist).
  whitelist:
    # Allows to define if the specified list of methods, fields, constructors or classes should be append to the default one or should replace it.
    # We recommend you to always choose 'append' unless you absolutely know what you are doing.
    mode: append
    # Define the list of classes, methods, constructors, fields or annotations to append (or set) to made accessible to the Groovy Script.
    # start with 'method' to allow a specific method (complete signature).
    # start with 'class' to allow a complete class. All methods, constructors and fields of the class will then be accessible.
    # start with 'new' to allow a specific constructor (complete signature).
    # start with 'field' to allow access to a specific field of a class.
    # start with 'annotation' to allow use of a specific annotation.
    list:
      - class java.lang.String
      - class groovy.json.JsonSlurper
      - class groovy.json.JsonOutput
      - class org.codehaus.groovy.runtime.EncodingGroovyMethods

```

Result is already:
```
14:05:16.217 [vert.x-eventloop-thread-3] [] ERROR i.g.policy.groovy.GroovyPolicy - Unable to run Groovy script
java.lang.SecurityException: Failed to resolve method [ class groovy.json.JsonSlurper parseText java.lang.Object ]
	at io.gravitee.policy.groovy.sandbox.SecuredInterceptor.onMethodCall(SecuredInterceptor.java:48)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$1.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
	at 28ea1d8696aa6b49d993ddaa9cd0b497e9577526.run(28ea1d8696aa6b49d993ddaa9cd0b497e9577526:20)
	at io.gravitee.policy.groovy.sandbox.SecuredGroovyShell.evaluate(SecuredGroovyShell.java:99)

```

**Comment by Emmanuel35** [comment]
Same with:
```
groovy:
  # Allows to define which methods, fields, constructors, annotations or classes are accessible to the Groovy Script (/!\ caution, changing default whitelist may expose you to security issues).
  # A complete list of default whitelist methods can be found here (https://raw.githubusercontent.com/gravitee-io/gravitee-policy-groovy/master/src/main/resources/groovy-whitelist).
  whitelist:
    # Allows to define if the specified list of methods, fields, constructors or classes should be append to the default one or should replace it.
    # We recommend you to always choose 'append' unless you absolutely know what you are doing.
    mode: append
    # Define the list of classes, methods, constructors, fields or annotations to append (or set) to made accessible to the Groovy Script.
    # start with 'method' to allow a specific method (complete signature).
    # start with 'class' to allow a complete class. All methods, constructors and fields of the class will then be accessible.
    # start with 'new' to allow a specific constructor (complete signature).
    # start with 'field' to allow access to a specific field of a class.
    # start with 'annotation' to allow use of a specific annotation.
    list:
      - class java.lang.String
      - class groovy.json.JsonSlurper
      - class groovy.json.JsonOutput
      - class org.codehaus.groovy.runtime.EncodingGroovyMethods
      # Ex: allow access to DateTimeFormatter.ofLocalizedDate(FormatStyle) method
      # - method java.time.format.DateTimeFormatter ofLocalizedDate java.time.format.FormatStyle
      - method groovy.json.JsonSlurper parseText java.lang.Object
      - method org.codehaus.groovy.runtime.EncodingGroovyMethods md5 java.lang.CharSequence

```

**Comment by brasseld** [comment]
Hi @Emmanuel35 

Can you share your groovy script and maybe a request payload.

There is no reference to the `JsonSlurper` in your first example so I suppose something has changed there?

**Comment by Emmanuel35** [comment]
Yes, I have also a script for JSON.

```
import groovy.json.JsonSlurper
import groovy.json.JsonOutput
 
class Hero {
    Integer id
    String name
}
   
class Reponse {
	Integer offset
	Integer limit
	Integer total
	Integer count
  	def heros = []
}
  
def reponseSimplifiee = new Reponse()
 
def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(response.content)
```

**Comment by jhaeyaert** [comment]
Hi @Emmanuel35, I just tested with the 2 provided examples:

```groovy
def ts = new Date()
ts = ts.getTime().toString()
request.parameters.'ts' = ts
 
def pubKey = 'aaaa'
def privKey = 'bbbb'
 
def hash = (ts + privKey + pubKey).md5()
```

and 

```groovy
import groovy.json.JsonSlurper
import groovy.json.JsonOutput
 
class Hero {
    Integer id
    String name
}
   
class Reponse {
	Integer offset
	Integer limit
	Integer total
	Integer count
  	def heros = []
}
  
def reponseSimplifiee = new Reponse()
 
def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(response.content).toString() // Note: you must assign a string content
```

With the following minimalist configuration:

```yaml
groovy:
  whitelist:
    list:
       - method org.codehaus.groovy.runtime.EncodingGroovyMethods md5 java.lang.CharSequence
```

And It works, no more 500 error. The first example successfully return a md5:

```bash
curl  http://127.0.0.1:8082/example
13cbd3a52c5ab980d320e1a95e4b16ac%
```

It's strange that your second stacktrace complain about JsonSlurper which is whitelisted by default. Can you tell us what version of the groovy policy you use ? (should be `1.11.1`).
