### ISSUE TITLE
[management-api] Finest configuration for SMTP server

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#488]
Some SMTP providers are requiring additional properties to be set.
Following snippet is an example for Gmail:
```yaml
email:
  enabled: true
  host: smtp.gmail.com
  port: 587
  from: gravitee@gmail.com
  username: brasseld@gmail.com
  password: fbihhwwistlfwkfz
  properties:
    auth: true
    starttls.enable: true
```

We must provide a way to provide these additional properties in `gravitee.yml`
