### ISSUE TITLE
[Helm Chart] Unable to override mongodb parameters if URI specified in `gravitee.yml`

### ISSUE THREAD

**Issue by Samaruq** [gravitee-io/issues#4922]
Currently, the section for mongodb inside the configmap template for the gateway looks like this:
```yaml
      mongodb:
        {{- if .Values.mongo.uri }}
        uri: {{ .Values.mongo.uri }}
        {{ else }}
        uri: mongodb://{{- if (eq .Values.mongo.auth.enabled true) }}{{ .Values.mongo.auth.username }}:{{ .Values.mongo.auth.password }}@{{- end }}{{ .Values.mongo.dbhost }}:{{ .Values.mongo.dbport }}/{{ .Values.mongo.dbname }}?{{- if .Values.mongo.rsEnabled }}&replicaSet={{ .Values.mongo.rs }}{{- end }}{{- if (eq .Values.mongo.auth.enabled true) }}&authSource={{ .Values.mongo.auth.source }}{{- end }}{{- if .Values.mongo.connectTimeoutMS }}&connectTimeoutMS={{ .Values.mongo.connectTimeoutMS }}{{- end }}
        {{- end }}
```
which puts a fully specified mongo URI in the gateway's `gravitee.yml`. In orde to not leak the password, our password is loaded from a kubernetes secret via env variables. In this case `gravitee_management_mongodb_password` is set for the Gateway pod.  However, authentication fails.

On the other hand, the configmap template for the api pod looks like this:
```yaml
      mongodb:
        sslEnabled: {{ .Values.mongo.sslEnabled }}
        socketKeepAlive: {{ .Values.mongo.socketKeepAlive }}
        {{- if .Values.mongo.uri }}
        uri: {{ .Values.mongo.uri }}
        {{- else if .Values.mongo.servers }}
        servers:
          {{- .Values.mongo.servers | nindent 10 }}
        dbname: {{ .Values.mongo.dbname }}
        {{- if (eq .Values.mongo.auth.enabled true) }}
        username: {{ .Values.mongo.auth.username }}
        password: {{ .Values.mongo.auth.password }}
        {{- end }}
        {{- else }}
        uri: mongodb://{{- if (eq .Values.mongo.auth.enabled true) }}{{ .Values.mongo.auth.username }}:{{ .Values.mongo.auth.password }}@{{- end }}{{ .Values.mongo.dbhost }}:{{ .Values.mongo.dbport }}/{{ .Values.mongo.dbname }}?{{- if .Values.mongo.rsEnabled }}&replicaSet={{ .Values.mongo.rs }}{{- end }}{{- if (eq .Values.mongo.auth.enabled true) }}&authSource={{ .Values.mongo.auth.source }}{{- end }}{{- if .Values.mongo.connectTimeoutMS }}&connectTimeoutMS={{ .Values.mongo.connectTimeoutMS }}{{- end }}
        {{- end }}
```
where depending on what is inside your `values.yaml`, the URI is only used if you specified it, as a last resort. 

In summary, the mongo authentication succeeds on the api pod but not on the gateway pod which use the same `values.yaml` as credentials source. The only difference is the way the templates are setup which leads me to believe, if you specify a mongo URI, no env var overriding is possible.

### Expected Behavior
Mongodb password should be overwritten by environment variable inside gateway pod like it does for the api pod.

### Current Behavior
Mongodb password is not overwritten.

### Possible Solution
Update helm chart, i.e. update gateway configmap template to look like the api configmap template. See above.

### Steps to Reproduce (for bugs)
1. Create k8s secret with mongodb password
2. Add following env var to gateway pod:
  ```yaml
     - name: gravitee_management_mongodb_password                                                                                                                                                        
       valueFrom:                                                                                                                                                                                        
         secretKeyRef:                                                                                                                                                                                   
           name: gravitee                                                                                                                                                                                
           key: mongodb-password
  ```
3. See authentication fail because password is not overwritten by env var.

### Context
We want to use helm and load passwords from k8s secrets.

### Your Environment
* Version used: APIM 3.5.1
* Helm v3
