### ISSUE TITLE
[repository] [redis] Configuration example

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#494]
Can you provide an example of a configuration of gravitee.io with redis as the repository?
How does a redis config in gravitee.yml look like instead of mongodb (as is per default):

```
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
```
