### ISSUE TITLE
[idp] httpClient proxy is never used

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5048]
Since #4396, it is possible to define a global http proxy to be used by all identity providers.

Due to a misconfiguration, the proxy, even if it is well defined, is never enabled except if we add the following VM option `-DhttpClient.proxy`. This VM option is not documented and doesn't make sense regarding the way the proxy should be configured:

```yaml
httpClient:
  timeout: 10000 # in milliseconds
  proxy:
    type: HTML #HTTP, SOCK4, SOCK5
    http:
      host: localhost
      port: 3128
      ...
```

We need to introduce a new boolean property `httpClient.proxy.enabled` (`false` by default).
