### ISSUE TITLE
[feature] Allow to configure groups and roles from your gravitee.yml

### ISSUE THREAD

**Issue by samaruq** [gravitee-io/issues#5049]
Let admins configure their Groups and Roles from the `gravitee.yml`.

### Expected Behavior
I don't know exactly in what section of the `gravitee.yml`  the groups and roles configuration should be put.

For groups you can have a list like this:
```yaml
groups:
  - name: API Admins
    defaultApiRole: 
      value: Owner
      allowChange: false
    defaultAppRole: 
      value: User
      allowChange: false
    invitations:
      email: true
      userSearch: true
    maxMembers: 0    # zero for unlimited
    notifications: true
    associations:
      newApis: true
      newApps: true
      existingApis: true
      existingApps: true
    groupAdmins:
      - admin_identifier1
      - admin_identifier2
  - name: APP Admins
  ...
```

For roles
```yaml
roleManagement:
  createDefaultRoles: false
  apiScope:
    defaultRole: User
    roles:
      - name: Owner
        description: This role can manage an API
        permissions:
          alert: [create, read, update,delete]
          analytics: [create, read, update, delete]
          ...
         subscription: [create, read, update, delete]
  environmentScope:
    default: User
    - name: Admin
      permissions:
        ...   
```
### Current Behavior
Currently not supported.

### Context
This allows for a more IaC approach to your Gravitee deployment.
Instead of having to document what groups and roles to create and setup,
you can specify all that information in your deployment files.
