### ISSUE TITLE
[helm] [gateway] manage X-Request-Id and X-Transaction-Id

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5199]
Currently those values are not defined by Values in the gateway-configmap.yaml file : 

```
     {{- if .Values.gateway.services.bridge.enabled }}
      bridge:
        http:
          enabled: true
          port: {{ .Values.gateway.services.bridge.service.internalPort }}
          host: 0.0.0.0
          authentication:
            type: basic
            users:
              {{ .Values.gateway.services.bridge.username }}: {{ .Values.gateway.services.bridge.password }}
      {{- end }}

    handlers:
      request:
        transaction:
          header: X-Gravitee-Transaction-Id
```
