### ISSUE TITLE
Gravitee | Portal-ui Error: Server unavailable or connection lost

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#5311]
Hello

I have run into a issue regarding the Portal-UI. I configured the Portal-UI and it worked perfectly at first. This means I was able to create a user via a e-mail and all the process after it. After trying it couple a minutes later the Portal-UI throws always the error on the dashboard that the server is unavailable or the connection is lost.

I am running Gravitee on a Linux Server.

This is what I added to my configuration to make the Portal-UI running:

```
/opt/graviteeio/apim/graviteeio-portal-ui-3.5.1/assets/config.json

{
  "baseURL": "http://xxxx.xxxx.xxxxxx.com:8085/portal/environments/DEFAULT",
  "loaderURL": "assets/images/gravitee-loader.gif",
  "pagination": {
    "size": {
      "default": 10,
      "values": [5, 10, 25, 50, 100]
    }
  }
}
```
---------------------------------------------------------------------------------------------------------------------------
```
/opt/graviteeio/apim/graviteeio-management-ui-3.5.1/constants.json

{
  "baseURL": "http://xxxx.xxxx.xxxxxx.com:8083/management/organizations/DEFAULT/environments/DEFAULT"
}
```
---------------------------------------------------------------------------------------------------------------------------

```
/opt/graviteeio/apim/graviteeio-rest-api-3.5.1/config/gravitee.yml
# The portal URL used in emails
portalURL: http://xxxx.xxxx.xxxxxx.com:8085/

# SMTP configuration used to send mails
email:
  enabled: true
  host: smtp.xx.xxxx.com
  subject: "[Gravitee - Infineon] %s"
  port: 25
  from: personalmail@xxxx.com
  username: myname@xxx.com
  password: 12345
  properties:
    auth: false
    starttls.enable: true
    ssl.trust: xxx.xx.xxxx.com

```

Inside the Dashboard under settings -> settings. Portal URL I added this:
http://xxxx.xxxx.xxxxxx.com:8085/

Now when I am trying to call the Portal via the http://xxxx.xxxx.xxxxxx.com:8085/ URl I am getting the previously mentioned error. 

![Capture](https://user-images.githubusercontent.com/59047274/112844844-76607000-90a4-11eb-8b75-a56400390ce7.PNG)

Looking inside the chrome debugger I am getting this error:
GET http://localhost:8083/portal/environments/DEFAULT/configuration/links 
net::ERR_CONNECTION_REFUSED

Why does it route to localhost:8083?

As said after the first configuration everything worked, but after looking in my config - again - and starting the services for Gravitee to run, it stopped working.

Now I don't know if I accidentally miss-configured something while looking into the config, but I am quite sure it looks the same as in the first configuration.

Kind regards,
/Ivo
