### ISSUE TITLE
[helm] [apim] Configure jwt / apikey policy

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5378]
We want to configure api-key / jwt policy from values like what is already done for api-key:

```
    # Customize the api-key header and / or query parameter.
    policy:
      api-key:
        header: {{ .Values.gateway.apiKey.header }}
        param: {{ .Values.gateway.apiKey.param }}
```
