### ISSUE TITLE
IM + APIM setup on docker-compose - "No endpoint matches the request URI." on OAuth2

### ISSUE THREAD

**Issue by raph1mm** [gravitee-io/issues#5636]
Hi,

I have setup IM and APIM from docker-compose from docs (with some modifications).

My API works just fine without Oauth2, but when I enable OAuth2 I'm keeping getting "No endpoint matches the request URI." 401 error.

### Your Environment

docker-compose for IM:

```
version: '3.5'

networks:
  frontend:
    name: frontend

services:
  nginx:
    image: nginx:1.16-alpine
    container_name: gio_am_nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - management
      - gateway
      - webui
    networks:
      - frontend

  mongodb_am:
    image: mongo:3.4
    container_name: gio_am_mongodb
    restart: always
    volumes:
      - ./datamongo:/data/db
      - ./logs/am-mongodb:/var/log/mongodb
    networks:
      - frontend

  gateway:
    image: graviteeio/am-gateway:${GIO_AM_VERSION}
    container_name: gio_am_gateway
    restart: always
    # links:
    #   - mongodb_am
    depends_on:
      - mongodb_am
    volumes:
      - ./logs/am-gateway:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    networks:
      - frontend

  management:
    image: graviteeio/am-management-api:${GIO_AM_VERSION}
    container_name: gio_am_management
    restart: always
    # links:
    #   - mongodb_am
    depends_on:
      - mongodb_am
    volumes:
      - ./logs/am-management-api:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    networks:
      - frontend

  webui:
    image: graviteeio/am-management-ui:${GIO_AM_VERSION}
    container_name: gio_am_webui
    restart: always
    depends_on:
      - management
    environment:
      - MGMT_API_URL=http://localhost:${NGINX_PORT}/am
      - MGMT_UI_URL=http://localhost:${NGINX_PORT}/am/ui
    volumes:
      - ./logs/am-webui:/var/log/httpd
    networks:
      - frontend

```

docker-compose for APIM:

```
version: '3.5'

networks:
  frontend:
    name: frontend
  storage:
    name: storage

volumes:
  data-elasticsearch:
  data-mongo:

services:
  mongodb:
    image: mongo:${MONGODB_VERSION:-3.6}
    container_name: gio_apim_mongodb
    restart: always
    volumes:
      - ./data-mongo:/data/db
      - ./logs/apim-mongodb:/var/log/mongodb
    networks:
      - storage

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.7.0}
    container_name: gio_apim_elasticsearch
    restart: always
    volumes:
      - ./data-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    networks:
      - storage

  gateway:
    image: graviteeio/apim-gateway:${APIM_VERSION:-3}
    container_name: gio_apim_gateway
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/apim-gateway:/opt/graviteeio-gateway/logs
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
    networks:
      - storage
      - frontend

  management_api:
    image: graviteeio/apim-management-api:${APIM_VERSION:-3}
    container_name: gio_apim_management_api
    restart: always
    ports:
      - "8083:8083"
    links:
      - mongodb
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/apim-management-api:/opt/graviteeio-management-api/logs
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
    networks:
      - storage
      - frontend

  management_ui:
    image: graviteeio/apim-management-ui:${APIM_VERSION:-3}
    container_name: gio_apim_management_ui
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - management_api
    environment:
      - MGMT_API_URL=http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/
    volumes:
      - ./logs/apim-management-ui:/var/log/nginx
    networks:
      - frontend

  portal_ui:
    image: graviteeio/apim-portal-ui:${APIM_VERSION:-3}
    container_name: gio_apim_portal_ui
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - management_api
    environment:
      - PORTAL_API_URL=http://localhost:8083/portal/environments/DEFAULT
    volumes:
      - ./logs/apim-portal-ui:/var/log/nginx
    networks:
      - frontend
```

In AM I have setup "backend to backend" application type.  Getting authentication token works fine.

In APIM I have this API:

```json
{
  "name": "XXX JSON-API",
  "version": "1.0.0",
  "visibility": "PUBLIC",
  "gravitee": "2.0.0",
  "flow_mode": "DEFAULT",
  "flows": [
    {
      "name": "",
      "path-operator": {
        "operator": "EQUALS",
        "path": "/v1/XXXX/referral/rfaUsage"
      },
      "condition": "",
      "methods": [
        "GET"
      ],
      "pre": [],
      "post": [],
      "enabled": true
    },
    {
      "name": "",
      "path-operator": {
        "operator": "EQUALS",
        "path": "/v1/XXXX/AAAA"
      },
      "condition": "",
      "methods": [
        "PATCH"
      ],
      "pre": [],
      "post": [],
      "enabled": true
    }
  ],
  "resources": [
    {
      "name": "am",
      "type": "oauth2-am-resource",
      "enabled": true,
      "configuration": {
        "type": "oauth2-am-resource",
        "enabled": true,
        "useSystemProxy": false,
        "version": "V1_X",
        "userClaim": "sub",
        "serverURL": "http://nginx/am",
        "securityDomain": "xxx",
        "clientId": "XXX",
        "clientSecret": "XXX"
      }
    }
  ],
  "properties": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "roles": [
        "a2a309ed-0cc4-4f72-a309-ed0cc42f7263"
      ]
    }
  ],
  "pages": [
    {
      "id": "5d7c278d-beb8-40fc-bc27-8dbeb8a0fcf6",
      "name": "Aside",
      "type": "SYSTEM_FOLDER",
      "order": 0,
      "published": true,
      "visibility": "PUBLIC",
      "lastModificationDate": 1621866400922,
      "contentType": "application/json",
      "homepage": false,
      "parentPath": "",
      "excludedAccessControls": false,
      "accessControls": [],
      "api": "32eb1283-d4d1-466e-ab12-83d4d1f66e7b"
    }
  ],
  "plans": [
    {
      "id": "17335372-8dbc-4123-b353-728dbcc12399",
      "name": "OA",
      "description": "OA",
      "validation": "MANUAL",
      "security": "OAUTH2",
      "securityDefinition": "{\"extractPayload\":false,\"checkRequiredScopes\":false,\"modeStrict\":false,\"propagateAuthHeader\":false,\"oauthResource\":\"am\"}",
      "type": "API",
      "status": "PUBLISHED",
      "api": "32eb1283-d4d1-466e-ab12-83d4d1f66e7b",
      "order": 1,
      "characteristics": [],
      "created_at": 1621871282933,
      "updated_at": 1621871295104,
      "published_at": 1621871295104,
      "paths": {},
      "flows": [
        {
          "name": "",
          "path-operator": {
            "operator": "STARTS_WITH",
            "path": "/"
          },
          "condition": "",
          "methods": [],
          "pre": [
            {
              "name": "OAuth2",
              "description": "",
              "enabled": true,
              "policy": "oauth2",
              "configuration": {
                "extractPayload": false,
                "checkRequiredScopes": false,
                "modeStrict": false,
                "propagateAuthHeader": false,
                "oauthResource": "am"
              }
            }
          ],
          "post": [],
          "enabled": true
        }
      ],
      "comment_required": false
    }
  ],
  "metadata": [
    {
      "key": "email-support",
      "name": "email-support",
      "format": "MAIL",
      "value": "${(api.primaryOwner.email)!''}",
      "defaultValue": "support@change.me",
      "apiId": "32eb1283-d4d1-466e-ab12-83d4d1f66e7b"
    }
  ],
  "id": "32eb1283-d4d1-466e-ab12-83d4d1f66e7b",
  "path_mappings": [
    "/v1/XXXX/referral/rfaUsage",
    "/v1/XXXX/AAAA"
  ],
  "proxy": {
    "virtual_hosts": [
      {
        "path": "/ccccc/api"
      }
    ],
    "strip_context_path": false,
    "preserve_host": false,
    "logging": {
      "mode": "CLIENT_PROXY",
      "content": "HEADERS_PAYLOADS",
      "scope": "REQUEST_RESPONSE"
    },
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "https://xxx-api-host.pl/api",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "http": {
              "connectTimeout": 5000,
              "idleTimeout": 60000,
              "keepAlive": true,
              "readTimeout": 10000,
              "pipelining": false,
              "maxConcurrentConnections": 100,
              "useCompression": true,
              "followRedirects": false
            },
            "proxy": {
              "enabled": false,
              "useSystemProxy": false,
              "host": "null",
              "port": 0,
              "type": "HTTP"
            },
            "ssl": {
              "trustAll": true,
              "hostnameVerifier": false
            }
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  },
  "response_templates": {},
  "primaryOwner": {
    "id": "a76730f4-bb8b-42be-a730-f4bb8b52bef5",
    "displayName": "admin",
    "type": "USER"
  }
}
```

So I'm getting Oauth token:

```
{
  "access_token" : "eyJraWQiOiJkZWZhdWx0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwZGU4YjBkYS1jOWQ3LTQ4YTctYThiMC1kYWM5ZDc5OGE3NDUiLCJhdWQiOiIwZGU4YjBkYS1jOWQ3LTQ4YTctYThiMC1kYWM5ZDc5OGE3NDUiLCJkb21haW4iOiI5ZTVhZWY0MS04Y2I3LTQ4NjktOWFlZi00MThjYjc4ODY5ZDMiLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2FtXC8xbW1cL29pZGMiLCJleHAiOjE2MjE5NDM5MzAsImlhdCI6MTYyMTkzNjczMCwianRpIjoid2lZeFJoQlluVU5BZjF5M3JuNklHaG1iSkxJWlpIQnFmcEhuOUx4TlRqUSJ9.xUu4ipa4lY6X-GtT2k3wKbviv6mHK381aiKXxFIr5munut4wOVV5Sp3bRcPdMHTKYCIRp0eCa20PRva1wXkVWGnIopPjPTj8uEeCACer88eUTzA2QrxVI1GYhsfc3fCKM9vDrFgx5kgFunXvLQrTVsH0gkKErTFYfYuLYJGIvN2u71MQq74nFjO8bneUNG0i15PvuhtPcr8J13tplmaWr47Y26mSrX07cGh7GWgNXKzCWbwTKikXGIQR81CKJIVW_3QvILzTFXwgVQ3IE7qRUfdvk6vi7qv-9cqiFRqYYj6caW0c_9XWa7jze5BgI9DZ0xGpRICiG28eQFrlVlsIkw",
  "token_type" : "bearer",
  "expires_in" : 7199
}
```

and then I'm trying to request API via gateway:

```
curl --location --request PATCH 'http://localhost:8082/ccccc/api/v1/XXX/AAAA' \           
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--header 'Authorization: Bearer "eyJraWQiOiJkZWZhdWx0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwZGU4YjBkYS1jOWQ3LTQ4YTctYThiMC1kYWM5ZDc5OGE3NDUiLCJhdWQiOiIwZGU4YjBkYS1jOWQ3LTQ4YTctYThiMC1kYWM5ZDc5OGE3NDUiLCJkb21haW4iOiI5ZTVhZWY0MS04Y2I3LTQ4NjktOWFlZi00MThjYjc4ODY5ZDMiLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2FtXC8xbW1cL29pZGMiLCJleHAiOjE2MjE5NDM5MzAsImlhdCI6MTYyMTkzNjczMCwianRpIjoid2lZeFJoQlluVU5BZjF5M3JuNklHaG1iSkxJWlpIQnFmcEhuOUx4TlRqUSJ9.xUu4ipa4lY6X-GtT2k3wKbviv6mHK381aiKXxFIr5munut4wOVV5Sp3bRcPdMHTKYCIRp0eCa20PRva1wXkVWGnIopPjPTj8uEeCACer88eUTzA2QrxVI1GYhsfc3fCKM9vDrFgx5kgFunXvLQrTVsH0gkKErTFYfYuLYJGIvN2u71MQq74nFjO8bneUNG0i15PvuhtPcr8J13tplmaWr47Y26mSrX07cGh7GWgNXKzCWbwTKikXGIQR81CKJIVW_3QvILzTFXwgVQ3IE7qRUfdvk6vi7qv-9cqiFRqYYj6caW0c_9XWa7jze5BgI9DZ0xGpRICiG28eQFrlVlsIkw' \
--data-raw '{
    "mail": "test@test.com",
    "password": "pass"
}'
```

and I'm getting:

`No endpoint matches the request URI`

Am I missing something here?
