### ISSUE TITLE
Helm charts should support specifying custom liveness and readiness probes

### ISSUE THREAD

**Issue by geoffreytran** [gravitee-io/issues#5660]
The current liveness and readiness probes are hard coded in the helm charts for services like the gateway and the api services. This prevents changing the probes to using the internal health check API's which are necessary to check if a gateway has full loaded all its API configuration before Kubernetes starts sending traffic through the gateway. Liveness and readiness probes should be customizable.

### Expected Behavior
Modify chart to allow customization of liveness and readiness probes.

https://github.com/bitnami/charts/blob/master/bitnami/keycloak
This chart and all bitnami charts allow for customization of the probes using the following pattern.

```
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
```

values.yaml
```yaml
livenessProbe:
  enabled: true
  httpGet:
    path: /auth/
    port: http
  initialDelaySeconds: 300
  periodSeconds: 1
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: /auth/realms/master
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

## Custom Liveness probes for Keycloak
##
customLivenessProbe: {}

## Custom Rediness probes Keycloak
##
customReadinessProbe: {}
```

### Current Behavior
Current liveness and readiness probes are hardcoded to tcp ports and are not customizable.

### Context
Without the ability to customize the probes and while using autoscaling, new gateways come online and get traffic sent to them before they have fully had the API's synced. This causes traffic hitting the new gateway to return errors.
