### ISSUE TITLE
[management] allow to customize api entrypoint

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5780]
Access Management exposes its api under `/management` path. This path is currently not customizable. On the Api Management side the entrypoint can be overridden via configuration such as:

```yaml
http:
  api:
    entrypoint: /
    management:
      entrypoint: ${http.api.entrypoint}management
```

The idea is to provide such a configuration on AM to give some flexibility and be consistent between AM and APIM.
