### ISSUE TITLE
[APID][helm] API Designer Helm chart creates path with unessesary regex for APID API

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5797]
API Designer Helm chart creates path with an unnecessary regex for APID API's ingress

```
spec:

  rules:

    {{- range $host := .Values.api.ingress.hosts }}

    - host: {{ $host }}

      http:

        paths:

          - path: {{ $ingressPath }}(/|$)(.*)

            backend:

              serviceName: {{ $serviceAPIName }}

              servicePort: {{ $serviceAPIPort }}
```

When using Big-IP Container Ingress services, regex paths are disabled. In addition, it doesn't seem like the Regex is necessary here because {{ $ingressPath }}  should catch everything that  {{ $ingressPath }}(/|$)(.*) does.

### Your Environment

* Version used: APID 1.24.3 installed with Helm chart v
