### ISSUE TITLE
[SMTP] Add a keystore on SMTP Conf.

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#5823]
It's not possible to set a keystore on SMTP conf. like notifiers : 

```
smtp:
  enabled: true
  host: smtp.example.com
  port: 25
  from: info@example.com
  username: info@example.com
  password: example.com
  subject: "[gravitee] %s"
  properties:
    auth: true
    starttlsEnable: false
    #localhost: apim.example.com

notifiers:
  smtp:
    enabled: true
    host: ${email.host}
    subject: ${email.subject}
    port: ${email.port}
    from: ${email.from}
    username: ${email.username}
    password: ${email.password}
    # starttlsEnabled: false
    # ssl:
    #   trustAll: false
    #   keyStore:
    #   keyStorePassword:
```
