### ISSUE TITLE
[reporter] Add the ability to filter or rename properties / fields

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5831]
```yaml
reporters:
  file:
    type: json
    rename:
      application: app
    exclude: # supports wildcard (*) to exclude all fields
      - plan
      - request.path # supports nested fields
    include: # only if exclude is set to all (*)
      - api
```
