### ISSUE TITLE
[kubernetes] Support kubernetes from the gravitee.yml

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5887]
Currently, we are relying on kubernetes environment variables for defining configuration from secrets.
The idea is to manage directly from the gravitee.yml by using a specific syntax.

Something like:

```yaml
part1:
  credentials:
    password: kube://my_namespace/my_secret
```

or 

```yaml
part1:
  credentials:
    password:
      source: kubernetes:
      namespace: my_namespace
      secret: my_secret
```

(to be discussed)
