### ISSUE TITLE
[management-api] is the default app a standard feature?

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#591]
Some of our applications have the name "Default Application"
It looks like it was added in response to issue #208 
Is it mandatory for newcomers? can we disable that feature? the list of all applications is messy when you have lot of users. Admin users may think about a bug (like dropped subscriptions following an APIM upgrade...), but it's not.

Versions : 1.3 & 1.5.1

**Comment by brasseld** [comment]
You can disable the default app creation from configuration file (`gravitee.yml`) in the management-api:
```yml
user:
    login:
       # Create a default application when user connects to the portal for the very first time (default true)
       defaultApplication: false
```
