### ISSUE TITLE
JDBC Plugin missing

### ISSUE THREAD

**Issue by SlateDave** [gravitee-io/issues#5979]
Following this guide here:
https://docs.gravitee.io/am/current/am_installguide_repositories_jdbc.html#overview

and clicking on "Download the same version as your AM platform" leads to this empty folder:
https://download.gravitee.io/#graviteeio-am/plugins/repositories/gravitee-repository-jdbc/

Where am I supposed to download the plugin?

**Comment by tcompiegne** [comment]
Hi @SlateDave the plugin is included by default in the distribution. Nothing more to do except loading your jdbc driver.

**Comment by SlateDave** [comment]
Great! I've uploaded the driver from the website under plugins/ext/repository-am-jdbc/postgresql-42.2.23.jar

The guide says I should configure the config like so:
```yaml
management:
  type: jdbc             # repository type
  jdbc:                  # jdbc/r2dbc repository
    driver:              # jdbc driver
    host:                # database hostname or IP
    port:                # database listening port
    database:            # database name to connect to
    username:            # username
    password:            # password
```

What should I put in the field ``driver:              # jdbc driver`` now? I've tried ``postgresql-42.2.23`` as well as ``postgresql`` alone but I keep getting following error:

```
nested exception is java.lang.IllegalArgumentException: Could not find delegating driver [postgresql]
```
