### ISSUE TITLE
[management][gateway] http proxy host exclusion does not work when url contains invalid characters

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6032]
Since v3.5.5 of Access Management, when using an Http Identity Provider with an url such as `http://test.mycompany.com/login?username={#principal}&password={#credentials}` and the http proxy enabled with some excluded hosts
```
httpClient:
#  timeout: 10000 # in milliseconds
  proxy:
    enabled: true
    exclude-hosts: # list of hosts to exclude from proxy (wildcard hosts are supported)
      - '*.mycompany.com'
    type: HTTP #HTTP, SOCK4, SOCK5
```

Then the host exclusion will fail due to an invalid url (due to '{#xxxx}').

The idea is to exclude query parameter before extracting host from the provided url and comparing it to the list of excluded hosts.
