### ISSUE TITLE
[Management] Sanitize email option

### ISSUE THREAD

**Issue by vmargerin** [gravitee-io/issues#6115]
For security purposes, it could be interesting to be able to sanitize notification emails like Markdown pages.

For example, it could be enabled in **gravitee.yml** configuration file:

```yaml
notifiers:
  email:
    enabled: true
    host: ${email.host}
    subject: ${email.subject}
    port: ${email.port}
    sanitize: true
``` 

Version used: Gravitee APIM 3.9.2
