### ISSUE TITLE
[reporter-file] monitor logs (node-*) get empty if output is set to elasticsearch

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6564]
When enabling file reporter at the gateway level and set the output type to "elasticsearch", the associated monitor logs (node-*) are not fulfilled with values.
Instead if using "json" as the output format, they are correctly filled.

### Steps to Reproduce (for bugs)

1. Enable file reporter at the gateway level in gravitee.yml file as : 
```
  file:
    enabled: True # Is the reporter enabled or not (default to false)
    fileName: ${gravitee.home}/logs/%s-yyyy_mm_dd
    output: elasticsearch # Can be csv, json, elasticsearch or message_pack
```
2. Restart the gateway, make some calls to APIs and check the size of the reporting data (node-* will remain empty) : 
```
-rw-r--r--  1 gravitee  gravitee    4593 15 nov 17:35 log-2021_11_15.json
-rw-r--r--  1 gravitee  gravitee     743 15 nov 17:35 request-2021_11_15.json
-rw-r--r--  1 gravitee  gravitee       0 15 nov 17:34 health-check-2021_11_15.json
-rw-r--r--  1 gravitee  gravitee       0 15 nov 17:34 node-2021_11_15.json
```
3. Change the output type to "json" instead, and the node-* file will be filled : 
```
  file:
    enabled: True # Is the reporter enabled or not (default to false)
    fileName: ${gravitee.home}/logs/%s-yyyy_mm_dd
    output: json # Can be csv, json, elasticsearch or message_pack
```

```
-rw-r--r--  1 gravitee  gravitee    4439 15 nov 17:36 log-2021_11_15.json
-rw-r--r--  1 gravitee  gravitee    5075 15 nov 17:36 request-2021_11_15.json
-rw-r--r--  1 gravitee  gravitee    2163 15 nov 17:36 node-2021_11_15.json
-rw-r--r--  1 gravitee  gravitee       0 15 nov 17:36 health-check-2021_11_15.json
```

### Your Environment

* Version used: reproduced in APIM 3.10.4 but not in APIM 3.5.16
* Browser Name and version: N/A
* Operating System and version: N/A
