### ISSUE TITLE
[helm] reordering HPA metrics

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7077]
## :collision: Describe the bug
While using argoCD with Kustomize based on latest Helm charts to deploy Gravitee (APIM/AM) on an Openshift infrastructure
if  deployed "as is" helm charts (with mandatory modifications to make it work on Openshift of course) , there is an out of sync loop on argoCD, because Kubernetes is reordering HPA metrics (cpu and memory in that case) when interpreting the manifest, therefore argoCD has a different base and try to update indefinitely on Openshift side to be synced.

The issue is covered here : https://github.com/argoproj/argo-cd/issues/1079.

The current workaround is by adding a kustomize patch as :
```
patches:
# Workaround to re-order HPA metrics defined in Helm chart
# to be consistent in ArgoCD app diff
- target:
    kind: HorizontalPodAutoscaler
  patch: |
    - op: move
      from: /spec/metrics/0
      path: /spec/metrics/-
```

The purpose of this request is to change this order directly in the Gravitee helm charts
Both for AM and APIM

## :movie_camera: Useful information
![mceclip0](https://user-images.githubusercontent.com/79909781/153037615-7d4b18a1-7ed2-4f33-9aa1-3e1c67fa72a5.png)

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...
