### ISSUE TITLE
[gateway]  elasticsearch ilm index_mode is missing rollover_alias and first index is not created

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7110]
## :collision: Describe the bug
When enabling ilm index_mode in the gateway and setting an ilm policy, it is failing as the index.lifecycle.rollover_alias is not set in the associated template of the index.
In addition, the first index is not set with the expected naming (ie gravitee-request instead of gravitee-request-000001)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. In the gateway gravitee.yml file, enable the ilm and associate a policy as follows : 
```
  elasticsearch:
    enabled: true # Is the reporter enabled or not (default to true)
    endpoints:
      - http://${ds.elastic.host}:${ds.elastic.port}
    lifecycle:
      policy_property_name: index.lifecycle.name   #for openDistro, use 'opendistro.index_state_management.policy_id' instead of 'index.lifecycle.name'
      policies:
        request: hot_delete ## ILM policy for the gravitee-request-* indexes
    index: gravitee
    index_per_type: true
    index_mode: ilm         # "daily" indexes, suffixed with date. Or "ilm" managed indexes, without date

```
2. Add the following Policy in ElasticSearch : 
```
PUT _ilm/policy/hot_delete
{
  "policy": {                       
    "phases": {
      "hot": {                      
        "actions": {
          "rollover": {             
            "max_age": "5m"
          }
        }
      },
      "delete": {
        "min_age": "10m",           
        "actions": {
          "delete": {}              
        }
      }
    }
  }
}
```
3. Restart the gateway, make an API request and check the indexes in ES 
An index named `gravitee-request` is created. Expected to have a first index named `gravitee-request-000001`
4. From te ilm Policy, an error is raised after 10min as the rollover can not be performed : 
```
gio_apim_elasticsearch-3.10.9 | {"type": "server", "timestamp": "2022-02-14T17:39:50,214Z", "level": "ERROR", "component": "o.e.x.i.IndexLifecycleRunner", "cluster.name": "elasticsearch", "node.name": "bf909b7467fa", "message": "policy [hot_delete] for index [gravitee-request] failed on step [{\"phase\":\"hot\",\"action\":\"rollover\",\"name\":\"check-rollover-ready\"}]. Moving to ERROR step", "cluster.uuid": "ub17JkOZQk-9RqJi3Th1VQ", "node.id": "FEjyD8zISGyGvVG0XT2UQg" , 
gio_apim_elasticsearch-3.10.9 | "stacktrace": ["java.lang.IllegalArgumentException: setting [index.lifecycle.rollover_alias] for index [gravitee-request] is empty or not defined",
gio_apim_elasticsearch-3.10.9 | "at org.elasticsearch.xpack.core.ilm.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:55) [x-pack-core-7.7.0.jar:7.7.0]",
gio_apim_elasticsearch-3.10.9 | "at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:173) [x-pack-ilm-7.7.0.jar:7.7.0]",
gio_apim_elasticsearch-3.10.9 | "at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:329) [x-pack-ilm-7.7.0.jar:7.7.0]",
gio_apim_elasticsearch-3.10.9 | "at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:267) [x-pack-ilm-7.7.0.jar:7.7.0]",
gio_apim_elasticsearch-3.10.9 | "at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:183) [x-pack-core-7.7.0.jar:7.7.0]",
gio_apim_elasticsearch-3.10.9 | "at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:211) [x-pack-core-7.7.0.jar:7.7.0]",
```
A workaround is to manually create the first index and manually change the ilm policy to include the rollover_alias but not manageable in case of gateway restart. 

## :rainbow: Expected behaviour
Have ilm index mode setting works as daily index mode without manual operations
We may need to introduce a `policy_property_rollover_alias` as we have for `index.lifecycle.name` in the gravitee.yml

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***
tested in 3.10.9 and 3.10.10

## :link: Dependencies

Link a story or other related things...
