### ISSUE TITLE
[APIM]CORS no longer read only if configured in .yml file

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7326]
## :collision: Describe the bug
When we configure CORS in .yml file only for management the Allow Origin and Max age are no longer read only. We can modify them in the UI of the Console. And the .yml file is not fully taken into account by the management.

```
http:
  api:
    # Configure the listening path for the API. Default to /
    entrypoint: /
    # Configure Management API and Portal API.
    management:
      enabled: true
      entrypoint: ${http.api.entrypoint}management
      cors:
# Allows to configure the header Access-Control-Allow-Origin (default value: *)
# '*' is a valid value but is considered as a security risk as it will be opened to cross origin requests from anywhere.
       allow-origin: '*'
# Allows to define how long the result of the preflight request should be cached for (default value; 1728000 [20 days])
       max-age: 604800
# Which methods to allow (default value: OPTIONS, GET, POST, PUT, DELETE)
      allow-methods: "GET, DELETE, PATCH, POST, PUT, OPTIONS"
# Which headers to allow (default values: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With, If-Match, X-Xsrf-Token)
      allow-headers: "Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With, If-Match, X-Xsrf-Token, X-Recaptcha-Token"
```

## :sunrise_over_mountains: To Reproduce
1. Create/Import a simple API.
2. Configure CORS with the example above. 
3. Go to Organization Settings to CORS and see the issue.
4. By testing in 3.13.3 or 3.5.29 also you will see a different behavior compared to 3.15.4.

## :rainbow: Expected behaviour
Allow Origin and Max Age or all should be read only when we configure CORS in .yml file.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.4 on Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.4
