### ISSUE TITLE
Update API results in error due to "Path already covered"

### ISSUE THREAD

**Issue by eckilein** [gravitee-io/issues#7685]
## :collision: Describe the bug
We recently updated our gravitee from 3.10 to 3.17. In our environment we use ansible to setup the APIM and configure the APIs via Management API. Since the update we get an error when Updating our APIs, which were created around a minute earlier.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Deploy APIM v3.17
2. Create an API by sending a POST-request towards /apis/import
3. Update the API by sending a PUT-request towards /apis/{{api_id}}
(use the same gateway path)
```bash
{
  "message" : "The path [{{ your API path }}] is already covered by an other API.",
  "parameters" : {
    "contextPath" : "{{ your API path }}"
  },
  "technicalCode" : "api.contextPath.exists",
  "http_status" : 400
}
```

## :rainbow: Expected behaviour
I would expect a 200, and a changed API instead of 400

## Current behaviour
The error above. Tried on different APIs - error persists with different gateway paths.

## :movie_camera: Useful information
The ansible tasks for creation and update may be helpful:
```yaml
- name: Create FIWARE API Entry
  uri:
    method: POST
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/import"
    return_content: yes
    body_format: json
    body: |
      {
        "proxy": {
          "endpoints": [
            {
              "name":"default",
              "target":"http://orion.{{ inv_cm.fiware.context_mgmt_ns_name }}.svc.cluster.local:9200",
              "inherit":true
            }
          ],
          "context_path":"https://apim.{{ DOMAIN }}{{ am_apim_settings.orion_api_path }}"
        },
        "pages":[],
        "plans":[],
        "tags":[],
        "name":"FIWARE NGSI",
        "version":"1.0",
        "description":"FIWARE NGSI API for Orion Context Broker"
      }
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200,400
  register: fiwareAPI



- name: Update to final Values
  uri:
    method: PUT
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ fiwareAPI.json.id }}"
    return_content: yes
    body_format: json
    body: "{{ lookup('template', 'templates/10_apim_stack/apis/orion/orion_ngsi_v2.json.j2') }}"
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200
  when: fiwareAPI.status != 400
```

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.17
 - OS: k8s using ubuntu 20.04 nodes
 - Browser: none
