### ISSUE TITLE
Assign groups to user from oauth user infos on first login.

### ISSUE THREAD

**Issue by c4r1570p4e** [gravitee-io/issues#781]
When management-ui is plugged on oauth2 security provider, on first login, user is created in gravitee user repository with default roles for scopes MANAGEMENT and PORTAL : I want to do a new feature that associate groups to users from informations coming from oauth user infos.

In management-rest-api gravitee.yaml file, in oauth2 providers config, we must be able to configure "a mapping" from user info to given groups.

On this example : 

user info json response

```
{
  "sub":"248289761001",
  "name":"Jane Doe",
  "given_name":"Jane",
  "family_name":"Doe",
  "mail":"janedoe@example.com",
  "picture":"http://example.com/janedoe/me.jpg",
  "identity_provider_id": "idp_5",
  "job_id": "API_EVANGELIST",
  "service_id": "585252525"
}
```

gravity.yml
```
...
security:
  providers:  # authentication providers
    - type: oauth2
	...
      mapping:
        id: sub
        email: mail
        lastname: family_name
        firstname: given_name
        picture: picture
      groups:
        - mapping:
      	    condition: #jsonPath('profile', '$.identity_provider_id') == 'idp_5' && #jsonPath('profile', '$.job_id') != 'API_BREAKER'
      	    values: ["Example group", "soft user"]
        - mapping:
      	    condition: #jsonPath('profile', '$.identity_provider_id') == 'idp_6'
      	    values: ["Others"]
...
```

On first login of user janedoe@example.com, the user will be created and user is part of groups  "Example group" and  "soft user" because 
`   #jsonPath('profile', '$.identity_provider_id') == 'idp_5' && #jsonPath('profile', '$.job_id') != 'API_BREAKER' `
match on user info json.

All mapping rules are cumulative, exemple :

```
      groups:
        - mapping:
      	    condition: #jsonPath('profile', '$.identity_provider_id') == 'idp_5'
      	    values: ["Example group", "soft user"]
        - mapping:
      	    condition: #jsonPath('profile', '$.job_id') != 'API_BREAKER' 
      	    values: ["Others"]
```

User will be created and associated to api group "Example group" and application group  "soft user" and "Others"  because 
`   #jsonPath('profile', '$.identity_provider_id') == 'idp_5' 
`and 
`   #jsonPath('profile', '$.job_id') != 'API_BREAKER' 
`match on user info json.

Some others rules :
By default, with oauth2 provider, user is created in gravitee user repository with default roles for scopes MANAGEMENT and PORTAL, this behavior is disabled if 
```
      groups:
        - mapping:
		...
```
is present in oauth2 provider configuration, no roles or groups are given by default, if no mapping match user info : user is created without any roles and outside any groups.

if a condition can't be parsed/executed or a given group can't be found by his name, the user is not created and not connected, error is logged at ERROR level.
