### ISSUE TITLE
[GKO] Define ManagementContext

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7982]
## :rainbow: Feature

As a user, I want to create a ManagementContext to define an APIM environment (url + credentials) i want to manage with GKO

## :sunrise_over_mountains: Additional information

Example of ManagementContext CRD : 
````
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: dev-mgmt-ctx
spec:
  baseUrl: http://localhost:8083
  organizationId: [my_org]
  environmentId: [my_env]
  auth:
    bearerToken: xxxx-yyyy-zzzz
```` 

- Can be used in API CRD
- GKO should handle error code from the M-API and retrieve to log (`4xx`)
- We **must** define `organization` & `environment`
  - if no value provided for `organization` & `environment`, errors from GKO
- We don't want to handle default value there.

## Out of scope

Error handling from M-API, we just forward errors if any from M-API

## :superhero: Acceptance criteria

- [x] Given a valid ManagementContext then i can "connect" to the M-API when I use the GKO
- [x] Given an unvalid ManagementContext Then I get a `403` response code When I try to "connect"
- [x] Given a valid ManagementContext then i can reach the correct org/env when i've set them up in ManagementContext

## Documentation

- [x] What is a ManagementContext ?
- [x] How to define a ManagementContext ?
