### ISSUE TITLE
[GKO] Store credentials in K8 secrets

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7983]
## :rainbow: Feature

As a user, I want to store credentials/token from Kubernetes secret in order to improve security

## :sunrise_over_mountains: Additional information

- [K8 secrets documentation](https://kubernetes.io/docs/concepts/configuration/secret/)
- Default behavior is using secret but we can hardcode value 
- Comment on template for creating secrets
- User/password or bearer token credentials
- Default namespace is the GKO one, can be overwritten but not a good practice
- syntax for secret reference : 
```
secretRef:
    name: <SECRET_NAME>
    namespace: <NAMESPACE> #default value is the current GKO namespace, can be overwritten
```

## Out of scope 

- Use of third party secrets management tools (Keeper, Secrets, Volt...)

## 📖 Documentation

- How to add secrets ? 
- Good practices regarding credential/token management
- How to overwrite namespace ? why it is not a good practice ?

## :superhero: Acceptance criteria

- [ ] Given a ManagementContext referencing secrets for credentials then i can reach the right environment using GKO

**Comment by a-cordier** [comment]
```yaml
# Use this context if you are running APIM in K3d and GKO locally
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: dev-mgmt-ctx
  namespace: apim-dev
spec:
  baseUrl: http://localhost:9000
  environmentId: DEFAULT
  organizationId: DEFAULT
  auth:
    secretRef: <SECRET_NAME>

```
