### ISSUE TITLE
Handle Subscription service config in Helm Chart

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#8271]
The Subscription service can be configured via `gravitee.yaml` using the following keys: 
```yaml
  subscription:
    enabled: true
    pre-expiration-notification-schedule: x,y,z
```

However, there is no mapping of them in the Helm Chart: https://github.com/gravitee-io/helm-charts/blob/c150d1755a6b9e5b9a373925d62ab0d82b401525/apim/3.x/templates/api/api-configmap.yaml#L150-L149

We should add them to the template to be sure Helm users are able to configure them via Values.
