### ISSUE TITLE
[helm-charts] Management URL of API configmap does not accept special characters

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#8303]
In the API configmap, the `management.url` setting can be computed using the ingress of the management UI

Currently, it is defined like this:
`url: https://{{ index .Values.ui.ingress.hosts 0 }}{{ regexFind "/[a-zA-Z]+" .Values.ui.ingress.path }}/`

The problem is that if you define your ingress path with `/mgmt-ui`, your setting will be `https://<host>/mgmt/`

According to this link: https://www.urlencoder.io/learn/#url-encoding-percent-encoding
> A URL is composed from a limited set of characters belonging to the US-ASCII character set. These characters include digits (0-9), letters(A-Z, a-z), and a few special characters ("-", ".", "_", "~").

So we should change the regex in the configmap accordingly.

### Expected Behavior
if the UI ingress is defined like this:
```yaml
ingress:
  enabled: true
  path: /mgmt-ui
  hosts:
    - apim.example.com
```
then management.url should be `https://apim.example.com/mgmt-ui/`

### Current Behavior
if the UI ingress is defined like this:
```yaml
ingress:
  enabled: true
  path: /mgmt-ui
  hosts:
    - apim.example.com
```
then management.url is `https://apim.example.com/mgmt/`
