### ISSUE TITLE
Helm Parsing Error in Security Context for Alerting Engine

### ISSUE THREAD

**Issue by gigo1980** [gravitee-io/issues#8314]
## :collision: 
If you try to use your own security Context you have an invalid k8s yaml

## :sunrise_over_mountains: To Reproduce
Set "engine.runAsNonRoot: true"
Take a look at the generate deployment yaml.

## :rainbow: Expected behaviour
```yaml
          imagePullPolicy: Always
          securityContext: 
            runAsNonRoot: true
            runAsUser: 1001
          ports:
```

## Current behaviour
```yaml
          imagePullPolicy: AlwayssecurityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
````

We will create a pull request!
