### ISSUE TITLE
[gateway] Websocket subprotocol isn't forwarded to the endpoint

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#8324]
## :collision: Describe the bug

Websocket subprotocol isn't forwarded to the endpoint causing a 502 error when trying to connect.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Clone https://github.com/apollographql/docs-examples/tree/main/apollo-server/v3/subscriptions-graphql-ws
2. Go inside the directory and run `yarn && yarn start`, it will start the WS server on: `ws://localhost:4000/graphql`
3. Using Postman you should be able to connect to `ws://localhost:4000/graphql`, **set the header** `Sec-WebSocket-Protocol: graphql-transport-ws` and send the following message (within 3s otherwise you will be disconnected):
```json
{ 
  "type": "connection_init" 
}
```
You will receive: 
```json
{ 
  "type": "connection_ack" 
}
```

4. Activate Websocket in the `gravitee.yml` of the gateway:
```yml
http:
  websocket:
    enabled: true
    subProtocols: graphql-transport-ws
    perMessageWebSocketCompressionSupported: true
    perFrameWebSocketCompressionSupported: true
```
4. On Gravitee APIM, create an API with `ws://localhost:4000/graphql` as a backend endpoint 
6. Try to connect to it using the same method as in `3.`
7. 💥 You will receive an error: `Error: Unexpected server response: 502`

## :rainbow: Expected behaviour

Unable to connect, `graphql-transport-ws` protocol isn't forward

## Current behaviour

The connection should be ok

## :link: Dependencies

Also related to https://github.com/gravitee-io/issues/issues/8228
