### ISSUE TITLE
When apostrophe is present in email address, error occurs

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8349]
## :collision: Describe the bug

AM not allowing single quotes in user emails so this is the error when an email is with apostrophe.

When we try to connect with a user having a quote in the email we have this error:

technical_error: Value [tést@mail.com] is not a valid email

***Please complete the following information:***
 - Environment: [e.g. 3.17.3]

**Comment by tcompiegne** [comment]
@zveljanoski you can now use your own pattern to validate your email address (since 3.15.4 https://github.com/gravitee-io/issues/issues/7289) 

```
gravitee.yml

# User management configuration
user:
  email:
    policy:
      pattern: ^[a-zA-Z0-9_+-]+(?:\.[a-zA-Z0-9_+-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$
```

Regards
