### ISSUE TITLE
Access Manager: Email validation regex needs updating

### ISSUE THREAD

**Issue by mtwomey** [gravitee-io/issues#8350]
https://github.com/gravitee-io/gravitee-access-management/blob/2f202584e35956c0ab0ad4e82b81ee771bef9557/gravitee-am-service/src/main/java/io/gravitee/am/service/validators/email/EmailValidatorImpl.java#L33

The email validation regex above should be updated to match the referenced OWASP example - which allows for 15 character in the TLD. Right now it is only allowing 7 characters, which means many users can not register. There are lots of TLDs that are longer than seven characters:

https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

**Comment by tcompiegne** [comment]
Hi @mtwomey ,

Thanks for the feedback, we will update the default ASAP.

BTW you can also use your own pattern to validate the email address (see https://github.com/gravitee-io/issues/issues/7289) : 

```
gravitee.yml

# User management configuration
user:
  email:
    policy:
      pattern: ^[a-zA-Z0-9_+-]+(?:\.[a-zA-Z0-9_+-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$
```
 
Best regards
