### ISSUE TITLE
[Questions] MongoDb Database name + Elastic Search

### ISSUE THREAD

**Issue by k33g** [gravitee-io/issues#847]
👋 Hello, just a simple question: 

**About MongoDb:**

- How can I change the name of the mongodb database ? It's my first steps with Gravitee and I would like to deploy it on [Clever Cloud](https://www.clever-cloud.com/). There is a MongoDb addon but I can't choose myself the name of the database
- when I use a user and a password, what is the best way to connect to the database?

Can I do something like that? 

```yaml
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
    username: ${ds.mongodb.user}
    password: ${ds.mongodb.password}

ratelimit:
  type: mongodb
  mongodb:
    uri: mongodb://${ds.mongodb.user}:${ds.mongodb.password}@${ds.mongodb.host}:${ds.mongodb.port}/${ds.mongodb.dbname}
```

**About Elastic Search:**

- How can I tell to Gravitee that I use an url with https ?

```yaml
  # Elasticsearch reporter
  elasticsearch:
    enabled: true # Is the reporter enabled or not (default to true)
    hosts:
      - ${ds.elastic.user}:${ds.elastic.password}@${ds.elastic.host}
```

the Clever Cloud Elastic Search addon gives me these kind of informations:

```
Host: bob-elasticsearch.services.clever-cloud.com
User: bob
Password: morane
URL: https://bob:morane@bob-elasticsearch.services.clever-cloud.com/
```

And I'm note sure how to you it?

Thank you for your help 😄
