### ISSUE TITLE
 APIM Helm Chart always contain nginx annotations

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#8728]
# Describe the bug

Even if I use another ingress class than nginx (haproxy for example) and if I don't override the API annotations, I still have `nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"` in generated annotations.

# To Reproduce

Steps to reproduce the behaviour:
 1\. create a values file with 
 ```
 ingress:
 annotations:
 kubernetes.io/ingress.class: haproxy
 ```
 2\. generate the final value
 3\. you will see:
 ```
 ingress:
 annotations:
 kubernetes.io/ingress.class: haproxy
 nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\n"
 ```

# Expected behaviour

I expect to not see the nginx annotations if I don't use nginx
