### ISSUE TITLE
[helm] Gateway metrics service is not exposing externalPort

### ISSUE THREAD

**Issue by Mattue** [gravitee-io/issues#8860]
## :collision: Describe the bug
I'm trying to expose metrics service of gateway by providing following configuration under `gateway` in helm values

Using [docs](https://docs.gravitee.io/apim/3.x/apim_installguide_kubernetes.html), [helm-values](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/values.yaml) and [templates](https://github.com/gravitee-io/helm-charts/blob/72a136239bec0450c12e33ca552cf5b33cb05726/apim/3.x/templates/gateway/gateway-service.yaml)

```yaml
          services:
            core:
              http:
                enabled: true
                port: 18083
                host: 0.0.0.0
                authentication:
                  type: basic
                  password: xxx
                secured: false
              service:
                enabled: true
                type: ClusterIP
                externalPort: 18083
              ingress:
                enabled: true
                ingressClassName: "nginx"
                path: /_(.*)
                hosts:
                  - my.valid.host
                annotations: {}
            metrics:
              enabled: true
              prometheus:
                enabled: true
```

But only 8082 port is exposed, which is default gateway port to listen requests to custom API's

## :sunrise_over_mountains: To Reproduce
1. Deploy gateway and it's internal API's with config provided above using kuber
2. See that 18083 port is not exposed

## :rainbow: Expected behavior
Kuber to expose port 18083 so it's available outside pod

## Current behavior
Only 8082 port is exposed, metrics API's is not available outside of gateway pod

## :movie_camera: Useful information
1. 18083 port is not exposed for gateway internal apis
![изображение](https://user-images.githubusercontent.com/9050530/217055732-6e0178fb-5487-4fc2-9643-1ccc5c247149.png)

2. `netstat -l` in gateway pod 
![изображение](https://user-images.githubusercontent.com/9050530/217055892-405f8907-b1f1-47e9-84c7-494e311856d1.png)

3. for `gravitee-api` it's working fabulous
![изображение](https://user-images.githubusercontent.com/9050530/217056127-75aae44d-2959-42fc-9c7a-19cbeb476b13.png)

## :computer: Desktop:
 - Environment: Kubernetes, apim-helm apim3:3.1.59
 - OS: Ubuntu 18.04.6 TLS
 - APIM image: 3.18.18

Thanks in advance!
