### ISSUE TITLE
Enable ServiceMonitor option on all Helm charts with metrics (apim, am, ...)

### ISSUE THREAD

**Issue by lucasfcnunes** [gravitee-io/issues#9170]
## :rainbow: Feature

```yaml
...
  metrics:
    enabled: true
    serviceMonitor:     <-
      enabled: true     <-
...
```

Cilium example: https://github.com/cilium/cilium/blob/v1.14.0/install/kubernetes/cilium/templates/cilium-agent/servicemonitor.yaml

```yaml
{{- if and .Values.agent (not .Values.preflight.enabled) .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent
  namespace: {{ .Values.prometheus.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: cilium
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.prometheus.serviceMonitor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheus.serviceMonitor.interval | quote }}
    honorLabels: true
    path: /metrics
    {{- with .Values.prometheus.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  targetLabels:
  - k8s-app
{{- end }}
```

## :sunrise_over_mountains: Additional information

- GKO is the only chart that has it https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/config/prometheus/monitor.yaml
