### ISSUE TITLE
Gateway Helm Chart : Can't add extraInitContainers

### ISSUE THREAD

**Issue by meveno** [gravitee-io/issues#9435]
## Describe the bug
Can't

## To Reproduce
Steps to reproduce the behaviour:
1. Create values.yaml file with extraInitContainers

```
gateway:
  [ ... skipped yaml ... ]
  extraInitContainers:
    - name: "wait-for-elasticsearch"
      image: "busybox:1.36"
      command: ["sh", "-c", "until nc -z -v graviteeio-apim-elasticsearch-data.gravitee.svc.cluster.local 9200; do echo waiting for elasticsearch; sleep 2; done"]
```

2. Try to deploy or generate template :

```
helm template --debug \
  --namespace gravitee \
  --version 3.20.25 \
  --values values.yaml \
  apim graviteeio/apim3
```

3. See error

```
install.go:214: [debug] Original chart version: "3.20.25"
install.go:231: [debug] CHART PATH: /home/user/.cache/helm/repository/apim3-3.20.25.tgz

coalesce.go:237: warning: skipped value for elasticsearch.initContainers: Not a table.
coalesce.go:237: warning: skipped value for mongodb.initContainers: Not a table.
Error: template: apim3/templates/gateway/gateway-deployment.yaml:129:16: executing "apim3/templates/gateway/gateway-deployment.yaml" at <.>: wrong type for value; expected string; got []interface {}
helm.go:84: [debug] template: apim3/templates/gateway/gateway-deployment.yaml:129:16: executing "apim3/templates/gateway/gateway-deployment.yaml" at <.>: wrong type for value; expected string; got []interface {}
```

## Expected behaviour
Yaml template deployment for gateway contains initContainers

## Current behaviour
Helm can't deploy or generate template

## Environment

***What is the impacted version?***

Helm Chart Version 3.20.25

## Potential impacts
Can't add initContainers to gateway

**Comment by gaetanmaisse** [comment]
Can you try with the following syntax?
```yaml
gateway:
  [ ... skipped yaml ... ]
  extraInitContainers: | 
      name: "wait-for-elasticsearch"
      image: "busybox:1.36"
      command: ["sh", "-c", "until nc -z -v graviteeio-apim-elasticsearch-data.gravitee.svc.cluster.local 9200; do echo waiting for elasticsearch; sleep 2; done"]
```
