### ISSUE TITLE
When manually deleting indices in elasticsearch in ILM will not automatically recover

### ISSUE THREAD

**Issue by cschockaert** [gravitee-io/issues#9465]
## Describe the bug
When manually deleting indices in elasticsearch in ILM will not automatically recover
In ilm mode

## To Reproduce
Steps to reproduce the behaviour:

1. Configure gravitee in ilm mode and with an manually created ilm policy:
2. 
```
es:
  endpoints:
    - ...
  settings:
    number_of_shards: 2
    number_of_replicas: 1
    refresh_interval: 5s
  index_mode: ilm # Index mode normal (daily index) vs ILM (managed by ILM)
  lifecycle:
    enabled: true
    policyPropertyName: index.lifecycle.name   #for openDistro, use 'opendistro.index_state_management.policy_id' instead of 'index.lifecycle.name'
    policies:
      monitor: retain-30d
      request: retain-30d
      health: retain-30d
      log: retain-30d
```
3. Go to https://kibana/app/management/data/index_management/indices
4. Delete all indices named gravitee-log-* (you can see gravitee es reported created first indice gravitee-log-000001)
5. Make some request on gateways
6. Gateway will recreate an indice but not named gravitee-log-000001 but gravitee-log.
<img width="1544" alt="image" src="https://github.com/gravitee-io/issues/assets/8597973/9917c816-4ce9-4b5f-94e0-8f3a72a9fecb">
7. Restart gateways, elasticsearch reporter will not start due to that error:

```
10:13:24.433 [vert.x-eventloop-thread-0] [] ERROR i.g.e.client.http.HttpClient - Unable to create index and alias: status[400] template[{ "aliases": { "gravitee-log": { "is_write_index": true } } }] response[{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [gravitee-log]: an index or data stream exists with the same name as the alias"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [gravitee-log]: an index or data stream exists with the same name as the alias"},"status":400}]
  10:13:24.438 [vert.x-eventloop-thread-0] [] ERROR i.g.r.e.ElasticsearchReporter - An error occurs while creating index mapping template
  io.gravitee.elasticsearch.exception.ElasticsearchException: Unable to create index and alias
  	at io.gravitee.elasticsearch.client.http.HttpClient.lambda$createIndexWithAlias$16(HttpClient.java:364)
  	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:83)
  	at io.vertx.rxjava3.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:60)
  	at io.vertx.rxjava3.ext.web.client.HttpRequest$3.handle(HttpRequest.java:446)
  	at io.vertx.rxjava3.ext.web.client.HttpRequest$3.handle(HttpRequest.java:443)
  	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:400)
  	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:387)
  	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:365)
  	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:332)
  	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:294)
  	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:550)
  	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
  	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
  	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Unknown Source)
``
## Expected behaviour

Gravitee reporter should not recreate an indice named gravitee-log but recreate a first indice gravitee-log-XXXXXX (with rollover pattern)

## Current behaviour
Gravitee reporter recreate an indice named gravitee-log and it mess up the ILM and rollover system.

## Useful information
Screenshot, video, logs, other supporting material

## Environment
GKE
Gravitee 3.20.26 with helm chart 3.20.26
ES + Kibana 8.11 (with official es helm chart)

## Potential impacts
We lose all the new logs

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## Dependencies

Link a story or other related things...
