### ISSUE TITLE
SCIM api descriptor is wrong  for the patch statement (user and group) according to the RFC

### ISSUE THREAD

**Issue by LasneF** [gravitee-io/issues#9751]
## Describe the bug
the specification for Patch RFC is wrong and is not compliant to the RFC specification 

## To Reproduce
here 
here it is 
https://github.com/gravitee-io/gravitee-access-management/blob/master/docs/scim-api-descriptor.yml#L683

the patch operation value is describe as an object , 
```
  Operation:
    type: object
    properties:
      op:
        type: string
        description: Value indicates the operation to perform.
        enum: ["add", "replace", "remove"]
      path:
        type: string
        description: String containing an attribute path describing the target of the operation. The "path" attribute is OPTIONAL for "add" and "replace" and is REQUIRED for "remove" operations.
        example: "addresses[type eq \"work\"]"
      value:
        type: object
        description: Member whose content specifies the value to be added or replaced.
```

looking on the  [RFC 7644 on patch](https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2.1)  the value can be an object OR an array or a simple type like a String 

given the fact that array and object are 2 differents model the specification should be updated  , can be type leverging oneOf for instance , but a bit tricky as the specification is mentionned as swagger 2.0 

Notice that the Gravitee postman collection there 
https://github.com/gravitee-io/gravitee-access-management/blob/36e4c76d3c2bfb28ea2709d98f8a67207561b92a/postman/collections/graviteeio-am-scim-collection-app-version.json 

already leverage the capability that value is not an object but can be a string or an array 

cf request 
Patch user - add operation - complex attribute

is using 
```
{
     "schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations": [{
        "op":"Add",
        "path":"name",
        "value": {
            "middleName": "Jane"
        }
     }]
}
```
and Patch user - add operation - single attribute
```
{
     "schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations": [{
        "op":"Add",
        "path": "userType",
        "value": "Employee"
     }]

}
```
is leveraging simple string 

and Patch user - replace operation - multi-valued attribute 
```
{
     "schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations": [{
        "op":"Replace",
        "path": "emails",
        "value": [
            {
                "value": "bjensen2@example.com",
                "type": "work",
                "primary": true
            },
            {
                "value": "bjensen-home@example.com",
                "type": "home"
            }
        ]
     }]
}
```
is leveraging a an array 

## Potential impacts

partial implementation of the RFC not compliant with SCIM providers 
difference between implementation and API specification 
blocking call in case of payload validation
