### ISSUE TITLE
[docs] Elastic Curator files for index management

### ISSUE THREAD

**Issue by fabMrc** [gravitee-io/issues#981]
For ES 5.x I share you jinja2 template for ansible
as describe by es blog for optimizing data footprint
[elasticsearch-as-a-time-series-data-store](https://www.elastic.co/fr/blog/elasticsearch-as-a-time-series-data-store)

```sh
/usr/bin/curator --config /opt/curator/curator.yml /opt/curator/action-curator.yml
```

curator.yml :
```yaml
client:
  hosts:
{% for server in groups["es_servers"] %}
    - {{server}}
{% endfor %}
  port: 9200

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```
action-curator.yml :

```yaml
actions:
  1:
    action: forcemerge
    description: "Perform a forceMerge on selected indices to 'max_num_segments' per shard. Merge Days - 1 index for optimize disk space footprint on Elasticsearch TS"
    options:
      max_num_segments: 1
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: '^(gravitee-).*$'
      exclude: False
    - filtertype: age
      source: name
      direction: older
      unit: days
      unit_count: 1
      timestring: '%Y.%m.%d'
  2:
    action: delete_indices
    description: "Delete selected indices older than 'es_curator_window' days"
    options:
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: '^(gravitee-).*$'
      exclude: False
    - filtertype: age
      source: name
      direction: older
      unit: days
      unit_count: {{es_curator_window}}
      timestring: '%Y.%m.%d'
```
